// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: agent.proto

package agent

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
	"trpc.group/trpc-go/trpc-go/stream"
)

// START ======================================= Server Service Definition ======================================= START

// AgentServerService defines service.
type AgentServerService interface {
	// SocraticAsk ---------- P0：MVP ----------
	//  SocraticAsk 苏格拉底式问答
	SocraticAsk(ctx context.Context, req *SocraticAskReq) (*SocraticAskRsp, error)
	// QuerySocraticSession QuerySocraticSession 查询当前进行中的会话状态
	QuerySocraticSession(ctx context.Context, req *QuerySocraticSessionReq) (*QuerySocraticSessionRsp, error)
	// QuerySocraticHistory QuerySocraticHistory 查询苏格拉底对话历史
	QuerySocraticHistory(ctx context.Context, req *QuerySocraticHistoryReq) (*QuerySocraticHistoryRsp, error)
	// EndSession EndSession 结束当前会话
	EndSession(ctx context.Context, req *EndSessionReq) (*EndSessionRsp, error)
	// SocraticAskStream ---------- P1：流式体验 ----------
	//  SocraticAskStream 流式问答；请求复用 SocraticAskReq
	SocraticAskStream(*SocraticAskReq, AgentServer_SocraticAskStreamServer) error
	// QueryKnowledgeGapList ---------- P2：学生画像与教师端 ----------
	//  QueryKnowledgeGapList 查询学生自己的知识薄弱点
	QueryKnowledgeGapList(ctx context.Context, req *QueryKnowledgeGapListReq) (*QueryKnowledgeGapListRsp, error)
	// QueryTeacherDashboard QueryTeacherDashboard 查询教师端班级统计概览
	QueryTeacherDashboard(ctx context.Context, req *QueryTeacherDashboardReq) (*QueryTeacherDashboardRsp, error)
	// QueryTeacherSessionList QueryTeacherSessionList 查询教师端会话列表
	QueryTeacherSessionList(ctx context.Context, req *QueryTeacherSessionListReq) (*QueryTeacherSessionListRsp, error)
	// QueryTeacherSessionDetail QueryTeacherSessionDetail 查询教师端单个会话明细
	QueryTeacherSessionDetail(ctx context.Context, req *QueryTeacherSessionDetailReq) (*QueryTeacherSessionDetailRsp, error)
	// QueryTeacherKnowledgeGapList QueryTeacherKnowledgeGapList 查询教师端知识薄弱点列表
	QueryTeacherKnowledgeGapList(ctx context.Context, req *QueryTeacherKnowledgeGapListReq) (*QueryTeacherKnowledgeGapListRsp, error)
}

func AgentServerService_SocraticAsk_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SocraticAskReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AgentServerService).SocraticAsk(ctx, reqbody.(*SocraticAskReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AgentServerService_QuerySocraticSession_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QuerySocraticSessionReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AgentServerService).QuerySocraticSession(ctx, reqbody.(*QuerySocraticSessionReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AgentServerService_QuerySocraticHistory_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QuerySocraticHistoryReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AgentServerService).QuerySocraticHistory(ctx, reqbody.(*QuerySocraticHistoryReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AgentServerService_EndSession_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &EndSessionReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AgentServerService).EndSession(ctx, reqbody.(*EndSessionReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AgentServerService_SocraticAskStream_Handler(srv interface{}, stream server.Stream) error {
	m := new(SocraticAskReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServerService).SocraticAskStream(m, &agentServerSocraticAskStreamServer{stream})
}

type AgentServer_SocraticAskStreamServer interface {
	Send(*SocraticAskChunk) error
	server.Stream
}

type agentServerSocraticAskStreamServer struct {
	server.Stream
}

func (x *agentServerSocraticAskStreamServer) Send(m *SocraticAskChunk) error {
	return x.Stream.SendMsg(m)
}

func AgentServerService_QueryKnowledgeGapList_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryKnowledgeGapListReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AgentServerService).QueryKnowledgeGapList(ctx, reqbody.(*QueryKnowledgeGapListReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AgentServerService_QueryTeacherDashboard_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryTeacherDashboardReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AgentServerService).QueryTeacherDashboard(ctx, reqbody.(*QueryTeacherDashboardReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AgentServerService_QueryTeacherSessionList_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryTeacherSessionListReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AgentServerService).QueryTeacherSessionList(ctx, reqbody.(*QueryTeacherSessionListReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AgentServerService_QueryTeacherSessionDetail_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryTeacherSessionDetailReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AgentServerService).QueryTeacherSessionDetail(ctx, reqbody.(*QueryTeacherSessionDetailReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func AgentServerService_QueryTeacherKnowledgeGapList_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &QueryTeacherKnowledgeGapListReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AgentServerService).QueryTeacherKnowledgeGapList(ctx, reqbody.(*QueryTeacherKnowledgeGapListReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AgentServerServer_ServiceDesc descriptor for server.RegisterService.
var AgentServerServer_ServiceDesc = server.ServiceDesc{
	ServiceName:  "oj.agent.AgentServer",
	HandlerType:  ((*AgentServerService)(nil)),
	StreamHandle: stream.NewStreamDispatcher(),
	Methods: []server.Method{
		{
			Name: "/oj.agent.AgentServer/SocraticAsk",
			Func: AgentServerService_SocraticAsk_Handler,
		},
		{
			Name: "/oj.agent.AgentServer/QuerySocraticSession",
			Func: AgentServerService_QuerySocraticSession_Handler,
		},
		{
			Name: "/oj.agent.AgentServer/QuerySocraticHistory",
			Func: AgentServerService_QuerySocraticHistory_Handler,
		},
		{
			Name: "/oj.agent.AgentServer/EndSession",
			Func: AgentServerService_EndSession_Handler,
		},
		{
			Name: "/oj.agent.AgentServer/QueryKnowledgeGapList",
			Func: AgentServerService_QueryKnowledgeGapList_Handler,
		},
		{
			Name: "/oj.agent.AgentServer/QueryTeacherDashboard",
			Func: AgentServerService_QueryTeacherDashboard_Handler,
		},
		{
			Name: "/oj.agent.AgentServer/QueryTeacherSessionList",
			Func: AgentServerService_QueryTeacherSessionList_Handler,
		},
		{
			Name: "/oj.agent.AgentServer/QueryTeacherSessionDetail",
			Func: AgentServerService_QueryTeacherSessionDetail_Handler,
		},
		{
			Name: "/oj.agent.AgentServer/QueryTeacherKnowledgeGapList",
			Func: AgentServerService_QueryTeacherKnowledgeGapList_Handler,
		},
	},
	Streams: []server.StreamDesc{
		{
			StreamName:    "/oj.agent.AgentServer/SocraticAskStream",
			Handler:       AgentServerService_SocraticAskStream_Handler,
			ServerStreams: true,
		},
	},
}

// RegisterAgentServerService registers service.
func RegisterAgentServerService(s server.Service, svr AgentServerService) {
	if err := s.Register(&AgentServerServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("AgentServer register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedAgentServer struct{}

// SocraticAsk ---------- P0：MVP ----------
//
//	SocraticAsk 苏格拉底式问答
func (s *UnimplementedAgentServer) SocraticAsk(ctx context.Context, req *SocraticAskReq) (*SocraticAskRsp, error) {
	return nil, errors.New("rpc SocraticAsk of service AgentServer is not implemented")
}

// QuerySocraticSession QuerySocraticSession 查询当前进行中的会话状态
func (s *UnimplementedAgentServer) QuerySocraticSession(ctx context.Context, req *QuerySocraticSessionReq) (*QuerySocraticSessionRsp, error) {
	return nil, errors.New("rpc QuerySocraticSession of service AgentServer is not implemented")
}

// QuerySocraticHistory QuerySocraticHistory 查询苏格拉底对话历史
func (s *UnimplementedAgentServer) QuerySocraticHistory(ctx context.Context, req *QuerySocraticHistoryReq) (*QuerySocraticHistoryRsp, error) {
	return nil, errors.New("rpc QuerySocraticHistory of service AgentServer is not implemented")
}

// EndSession EndSession 结束当前会话
func (s *UnimplementedAgentServer) EndSession(ctx context.Context, req *EndSessionReq) (*EndSessionRsp, error) {
	return nil, errors.New("rpc EndSession of service AgentServer is not implemented")
}

// SocraticAskStream ---------- P1：流式体验 ----------
//
//	SocraticAskStream 流式问答；请求复用 SocraticAskReq
func (s *UnimplementedAgentServer) SocraticAskStream(req *SocraticAskReq, stream AgentServer_SocraticAskStreamServer) error {
	return errors.New("rpc SocraticAskStream of service AgentServer is not implemented")
}

// QueryKnowledgeGapList ---------- P2：学生画像与教师端 ----------
//
//	QueryKnowledgeGapList 查询学生自己的知识薄弱点
func (s *UnimplementedAgentServer) QueryKnowledgeGapList(ctx context.Context, req *QueryKnowledgeGapListReq) (*QueryKnowledgeGapListRsp, error) {
	return nil, errors.New("rpc QueryKnowledgeGapList of service AgentServer is not implemented")
}

// QueryTeacherDashboard QueryTeacherDashboard 查询教师端班级统计概览
func (s *UnimplementedAgentServer) QueryTeacherDashboard(ctx context.Context, req *QueryTeacherDashboardReq) (*QueryTeacherDashboardRsp, error) {
	return nil, errors.New("rpc QueryTeacherDashboard of service AgentServer is not implemented")
}

// QueryTeacherSessionList QueryTeacherSessionList 查询教师端会话列表
func (s *UnimplementedAgentServer) QueryTeacherSessionList(ctx context.Context, req *QueryTeacherSessionListReq) (*QueryTeacherSessionListRsp, error) {
	return nil, errors.New("rpc QueryTeacherSessionList of service AgentServer is not implemented")
}

// QueryTeacherSessionDetail QueryTeacherSessionDetail 查询教师端单个会话明细
func (s *UnimplementedAgentServer) QueryTeacherSessionDetail(ctx context.Context, req *QueryTeacherSessionDetailReq) (*QueryTeacherSessionDetailRsp, error) {
	return nil, errors.New("rpc QueryTeacherSessionDetail of service AgentServer is not implemented")
}

// QueryTeacherKnowledgeGapList QueryTeacherKnowledgeGapList 查询教师端知识薄弱点列表
func (s *UnimplementedAgentServer) QueryTeacherKnowledgeGapList(ctx context.Context, req *QueryTeacherKnowledgeGapListReq) (*QueryTeacherKnowledgeGapListRsp, error) {
	return nil, errors.New("rpc QueryTeacherKnowledgeGapList of service AgentServer is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// AgentServerClientProxy defines service client proxy
type AgentServerClientProxy interface {
	// SocraticAsk ---------- P0：MVP ----------
	//  SocraticAsk 苏格拉底式问答
	SocraticAsk(ctx context.Context, req *SocraticAskReq, opts ...client.Option) (rsp *SocraticAskRsp, err error)
	// QuerySocraticSession QuerySocraticSession 查询当前进行中的会话状态
	QuerySocraticSession(ctx context.Context, req *QuerySocraticSessionReq, opts ...client.Option) (rsp *QuerySocraticSessionRsp, err error)
	// QuerySocraticHistory QuerySocraticHistory 查询苏格拉底对话历史
	QuerySocraticHistory(ctx context.Context, req *QuerySocraticHistoryReq, opts ...client.Option) (rsp *QuerySocraticHistoryRsp, err error)
	// EndSession EndSession 结束当前会话
	EndSession(ctx context.Context, req *EndSessionReq, opts ...client.Option) (rsp *EndSessionRsp, err error)
	// SocraticAskStream ---------- P1：流式体验 ----------
	//  SocraticAskStream 流式问答；请求复用 SocraticAskReq
	SocraticAskStream(ctx context.Context, req *SocraticAskReq, opts ...client.Option) (AgentServer_SocraticAskStreamClient, error)
	// QueryKnowledgeGapList ---------- P2：学生画像与教师端 ----------
	//  QueryKnowledgeGapList 查询学生自己的知识薄弱点
	QueryKnowledgeGapList(ctx context.Context, req *QueryKnowledgeGapListReq, opts ...client.Option) (rsp *QueryKnowledgeGapListRsp, err error)
	// QueryTeacherDashboard QueryTeacherDashboard 查询教师端班级统计概览
	QueryTeacherDashboard(ctx context.Context, req *QueryTeacherDashboardReq, opts ...client.Option) (rsp *QueryTeacherDashboardRsp, err error)
	// QueryTeacherSessionList QueryTeacherSessionList 查询教师端会话列表
	QueryTeacherSessionList(ctx context.Context, req *QueryTeacherSessionListReq, opts ...client.Option) (rsp *QueryTeacherSessionListRsp, err error)
	// QueryTeacherSessionDetail QueryTeacherSessionDetail 查询教师端单个会话明细
	QueryTeacherSessionDetail(ctx context.Context, req *QueryTeacherSessionDetailReq, opts ...client.Option) (rsp *QueryTeacherSessionDetailRsp, err error)
	// QueryTeacherKnowledgeGapList QueryTeacherKnowledgeGapList 查询教师端知识薄弱点列表
	QueryTeacherKnowledgeGapList(ctx context.Context, req *QueryTeacherKnowledgeGapListReq, opts ...client.Option) (rsp *QueryTeacherKnowledgeGapListRsp, err error)
}

type AgentServerClientProxyImpl struct {
	client       client.Client
	streamClient stream.Client
	opts         []client.Option
}

var NewAgentServerClientProxy = func(opts ...client.Option) AgentServerClientProxy {
	return &AgentServerClientProxyImpl{client: client.DefaultClient, streamClient: stream.DefaultStreamClient, opts: opts}
}

func (c *AgentServerClientProxyImpl) SocraticAsk(ctx context.Context, req *SocraticAskReq, opts ...client.Option) (*SocraticAskRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.agent.AgentServer/SocraticAsk")
	msg.WithCalleeServiceName(AgentServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentServer")
	msg.WithCalleeMethod("SocraticAsk")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SocraticAskRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AgentServerClientProxyImpl) QuerySocraticSession(ctx context.Context, req *QuerySocraticSessionReq, opts ...client.Option) (*QuerySocraticSessionRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.agent.AgentServer/QuerySocraticSession")
	msg.WithCalleeServiceName(AgentServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentServer")
	msg.WithCalleeMethod("QuerySocraticSession")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QuerySocraticSessionRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AgentServerClientProxyImpl) QuerySocraticHistory(ctx context.Context, req *QuerySocraticHistoryReq, opts ...client.Option) (*QuerySocraticHistoryRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.agent.AgentServer/QuerySocraticHistory")
	msg.WithCalleeServiceName(AgentServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentServer")
	msg.WithCalleeMethod("QuerySocraticHistory")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QuerySocraticHistoryRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AgentServerClientProxyImpl) EndSession(ctx context.Context, req *EndSessionReq, opts ...client.Option) (*EndSessionRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.agent.AgentServer/EndSession")
	msg.WithCalleeServiceName(AgentServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentServer")
	msg.WithCalleeMethod("EndSession")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &EndSessionRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AgentServerClientProxyImpl) SocraticAskStream(ctx context.Context, req *SocraticAskReq, opts ...client.Option) (AgentServer_SocraticAskStreamClient, error) {
	ctx, msg := codec.WithCloneMessage(ctx)

	msg.WithClientRPCName("/oj.agent.AgentServer/SocraticAskStream")
	msg.WithCalleeServiceName(AgentServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentServer")
	msg.WithCalleeMethod("SocraticAskStream")
	msg.WithSerializationType(codec.SerializationTypePB)

	clientStreamDesc := &client.ClientStreamDesc{}
	clientStreamDesc.StreamName = "/oj.agent.AgentServer/SocraticAskStream"
	clientStreamDesc.ClientStreams = false
	clientStreamDesc.ServerStreams = true

	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)

	stream, err := c.streamClient.NewStream(ctx, clientStreamDesc, "/oj.agent.AgentServer/SocraticAskStream", callopts...)
	if err != nil {
		return nil, err
	}
	x := &agentServerSocraticAskStreamClient{stream}
	if err := x.ClientStream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentServer_SocraticAskStreamClient interface {
	Recv() (*SocraticAskChunk, error)
	client.ClientStream
}

type agentServerSocraticAskStreamClient struct {
	client.ClientStream
}

func (x *agentServerSocraticAskStreamClient) Recv() (*SocraticAskChunk, error) {
	m := new(SocraticAskChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *AgentServerClientProxyImpl) QueryKnowledgeGapList(ctx context.Context, req *QueryKnowledgeGapListReq, opts ...client.Option) (*QueryKnowledgeGapListRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.agent.AgentServer/QueryKnowledgeGapList")
	msg.WithCalleeServiceName(AgentServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentServer")
	msg.WithCalleeMethod("QueryKnowledgeGapList")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryKnowledgeGapListRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AgentServerClientProxyImpl) QueryTeacherDashboard(ctx context.Context, req *QueryTeacherDashboardReq, opts ...client.Option) (*QueryTeacherDashboardRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.agent.AgentServer/QueryTeacherDashboard")
	msg.WithCalleeServiceName(AgentServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentServer")
	msg.WithCalleeMethod("QueryTeacherDashboard")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryTeacherDashboardRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AgentServerClientProxyImpl) QueryTeacherSessionList(ctx context.Context, req *QueryTeacherSessionListReq, opts ...client.Option) (*QueryTeacherSessionListRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.agent.AgentServer/QueryTeacherSessionList")
	msg.WithCalleeServiceName(AgentServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentServer")
	msg.WithCalleeMethod("QueryTeacherSessionList")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryTeacherSessionListRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AgentServerClientProxyImpl) QueryTeacherSessionDetail(ctx context.Context, req *QueryTeacherSessionDetailReq, opts ...client.Option) (*QueryTeacherSessionDetailRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.agent.AgentServer/QueryTeacherSessionDetail")
	msg.WithCalleeServiceName(AgentServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentServer")
	msg.WithCalleeMethod("QueryTeacherSessionDetail")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryTeacherSessionDetailRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *AgentServerClientProxyImpl) QueryTeacherKnowledgeGapList(ctx context.Context, req *QueryTeacherKnowledgeGapListReq, opts ...client.Option) (*QueryTeacherKnowledgeGapListRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/oj.agent.AgentServer/QueryTeacherKnowledgeGapList")
	msg.WithCalleeServiceName(AgentServerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AgentServer")
	msg.WithCalleeMethod("QueryTeacherKnowledgeGapList")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &QueryTeacherKnowledgeGapListRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
