// Code generated by MockGen. DO NOT EDIT.
// Source: stub/github.com/csuJudge/agentProto/agent/agent.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=stub/github.com/csuJudge/agentProto/agent/agent_mock.go -package=agent -self_package=github.com/csuJudge/agentProto/agent --source=stub/github.com/csuJudge/agentProto/agent/agent.trpc.go
//

// Package agent is a generated GoMock package.
package agent

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockAgentServerService is a mock of AgentServerService interface.
type MockAgentServerService struct {
	ctrl     *gomock.Controller
	recorder *MockAgentServerServiceMockRecorder
}

// MockAgentServerServiceMockRecorder is the mock recorder for MockAgentServerService.
type MockAgentServerServiceMockRecorder struct {
	mock *MockAgentServerService
}

// NewMockAgentServerService creates a new mock instance.
func NewMockAgentServerService(ctrl *gomock.Controller) *MockAgentServerService {
	mock := &MockAgentServerService{ctrl: ctrl}
	mock.recorder = &MockAgentServerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentServerService) EXPECT() *MockAgentServerServiceMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockAgentServerService) ISGOMOCK() struct{} {
	return struct{}{}
}

// EndSession mocks base method.
func (m *MockAgentServerService) EndSession(ctx context.Context, req *EndSessionReq) (*EndSessionRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndSession", ctx, req)
	ret0, _ := ret[0].(*EndSessionRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndSession indicates an expected call of EndSession.
func (mr *MockAgentServerServiceMockRecorder) EndSession(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndSession", reflect.TypeOf((*MockAgentServerService)(nil).EndSession), ctx, req)
}

// QueryKnowledgeGapList mocks base method.
func (m *MockAgentServerService) QueryKnowledgeGapList(ctx context.Context, req *QueryKnowledgeGapListReq) (*QueryKnowledgeGapListRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryKnowledgeGapList", ctx, req)
	ret0, _ := ret[0].(*QueryKnowledgeGapListRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryKnowledgeGapList indicates an expected call of QueryKnowledgeGapList.
func (mr *MockAgentServerServiceMockRecorder) QueryKnowledgeGapList(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryKnowledgeGapList", reflect.TypeOf((*MockAgentServerService)(nil).QueryKnowledgeGapList), ctx, req)
}

// QuerySocraticHistory mocks base method.
func (m *MockAgentServerService) QuerySocraticHistory(ctx context.Context, req *QuerySocraticHistoryReq) (*QuerySocraticHistoryRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuerySocraticHistory", ctx, req)
	ret0, _ := ret[0].(*QuerySocraticHistoryRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuerySocraticHistory indicates an expected call of QuerySocraticHistory.
func (mr *MockAgentServerServiceMockRecorder) QuerySocraticHistory(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySocraticHistory", reflect.TypeOf((*MockAgentServerService)(nil).QuerySocraticHistory), ctx, req)
}

// QuerySocraticSession mocks base method.
func (m *MockAgentServerService) QuerySocraticSession(ctx context.Context, req *QuerySocraticSessionReq) (*QuerySocraticSessionRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuerySocraticSession", ctx, req)
	ret0, _ := ret[0].(*QuerySocraticSessionRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuerySocraticSession indicates an expected call of QuerySocraticSession.
func (mr *MockAgentServerServiceMockRecorder) QuerySocraticSession(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySocraticSession", reflect.TypeOf((*MockAgentServerService)(nil).QuerySocraticSession), ctx, req)
}

// QueryTeacherDashboard mocks base method.
func (m *MockAgentServerService) QueryTeacherDashboard(ctx context.Context, req *QueryTeacherDashboardReq) (*QueryTeacherDashboardRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryTeacherDashboard", ctx, req)
	ret0, _ := ret[0].(*QueryTeacherDashboardRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryTeacherDashboard indicates an expected call of QueryTeacherDashboard.
func (mr *MockAgentServerServiceMockRecorder) QueryTeacherDashboard(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryTeacherDashboard", reflect.TypeOf((*MockAgentServerService)(nil).QueryTeacherDashboard), ctx, req)
}

// QueryTeacherKnowledgeGapList mocks base method.
func (m *MockAgentServerService) QueryTeacherKnowledgeGapList(ctx context.Context, req *QueryTeacherKnowledgeGapListReq) (*QueryTeacherKnowledgeGapListRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryTeacherKnowledgeGapList", ctx, req)
	ret0, _ := ret[0].(*QueryTeacherKnowledgeGapListRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryTeacherKnowledgeGapList indicates an expected call of QueryTeacherKnowledgeGapList.
func (mr *MockAgentServerServiceMockRecorder) QueryTeacherKnowledgeGapList(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryTeacherKnowledgeGapList", reflect.TypeOf((*MockAgentServerService)(nil).QueryTeacherKnowledgeGapList), ctx, req)
}

// QueryTeacherSessionDetail mocks base method.
func (m *MockAgentServerService) QueryTeacherSessionDetail(ctx context.Context, req *QueryTeacherSessionDetailReq) (*QueryTeacherSessionDetailRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryTeacherSessionDetail", ctx, req)
	ret0, _ := ret[0].(*QueryTeacherSessionDetailRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryTeacherSessionDetail indicates an expected call of QueryTeacherSessionDetail.
func (mr *MockAgentServerServiceMockRecorder) QueryTeacherSessionDetail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryTeacherSessionDetail", reflect.TypeOf((*MockAgentServerService)(nil).QueryTeacherSessionDetail), ctx, req)
}

// QueryTeacherSessionList mocks base method.
func (m *MockAgentServerService) QueryTeacherSessionList(ctx context.Context, req *QueryTeacherSessionListReq) (*QueryTeacherSessionListRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryTeacherSessionList", ctx, req)
	ret0, _ := ret[0].(*QueryTeacherSessionListRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryTeacherSessionList indicates an expected call of QueryTeacherSessionList.
func (mr *MockAgentServerServiceMockRecorder) QueryTeacherSessionList(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryTeacherSessionList", reflect.TypeOf((*MockAgentServerService)(nil).QueryTeacherSessionList), ctx, req)
}

// SocraticAsk mocks base method.
func (m *MockAgentServerService) SocraticAsk(ctx context.Context, req *SocraticAskReq) (*SocraticAskRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SocraticAsk", ctx, req)
	ret0, _ := ret[0].(*SocraticAskRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SocraticAsk indicates an expected call of SocraticAsk.
func (mr *MockAgentServerServiceMockRecorder) SocraticAsk(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SocraticAsk", reflect.TypeOf((*MockAgentServerService)(nil).SocraticAsk), ctx, req)
}

// SocraticAskStream mocks base method.
func (m *MockAgentServerService) SocraticAskStream(arg0 *SocraticAskReq, arg1 AgentServer_SocraticAskStreamServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SocraticAskStream", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SocraticAskStream indicates an expected call of SocraticAskStream.
func (mr *MockAgentServerServiceMockRecorder) SocraticAskStream(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SocraticAskStream", reflect.TypeOf((*MockAgentServerService)(nil).SocraticAskStream), arg0, arg1)
}

// MockAgentServer_SocraticAskStreamServer is a mock of AgentServer_SocraticAskStreamServer interface.
type MockAgentServer_SocraticAskStreamServer struct {
	ctrl     *gomock.Controller
	recorder *MockAgentServer_SocraticAskStreamServerMockRecorder
}

// MockAgentServer_SocraticAskStreamServerMockRecorder is the mock recorder for MockAgentServer_SocraticAskStreamServer.
type MockAgentServer_SocraticAskStreamServerMockRecorder struct {
	mock *MockAgentServer_SocraticAskStreamServer
}

// NewMockAgentServer_SocraticAskStreamServer creates a new mock instance.
func NewMockAgentServer_SocraticAskStreamServer(ctrl *gomock.Controller) *MockAgentServer_SocraticAskStreamServer {
	mock := &MockAgentServer_SocraticAskStreamServer{ctrl: ctrl}
	mock.recorder = &MockAgentServer_SocraticAskStreamServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentServer_SocraticAskStreamServer) EXPECT() *MockAgentServer_SocraticAskStreamServerMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockAgentServer_SocraticAskStreamServer) ISGOMOCK() struct{} {
	return struct{}{}
}

// Context mocks base method.
func (m *MockAgentServer_SocraticAskStreamServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockAgentServer_SocraticAskStreamServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockAgentServer_SocraticAskStreamServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockAgentServer_SocraticAskStreamServer) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockAgentServer_SocraticAskStreamServerMockRecorder) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockAgentServer_SocraticAskStreamServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockAgentServer_SocraticAskStreamServer) Send(arg0 *SocraticAskChunk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockAgentServer_SocraticAskStreamServerMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockAgentServer_SocraticAskStreamServer)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockAgentServer_SocraticAskStreamServer) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockAgentServer_SocraticAskStreamServerMockRecorder) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockAgentServer_SocraticAskStreamServer)(nil).SendMsg), m)
}

// MockAgentServerClientProxy is a mock of AgentServerClientProxy interface.
type MockAgentServerClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockAgentServerClientProxyMockRecorder
}

// MockAgentServerClientProxyMockRecorder is the mock recorder for MockAgentServerClientProxy.
type MockAgentServerClientProxyMockRecorder struct {
	mock *MockAgentServerClientProxy
}

// NewMockAgentServerClientProxy creates a new mock instance.
func NewMockAgentServerClientProxy(ctrl *gomock.Controller) *MockAgentServerClientProxy {
	mock := &MockAgentServerClientProxy{ctrl: ctrl}
	mock.recorder = &MockAgentServerClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentServerClientProxy) EXPECT() *MockAgentServerClientProxyMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockAgentServerClientProxy) ISGOMOCK() struct{} {
	return struct{}{}
}

// EndSession mocks base method.
func (m *MockAgentServerClientProxy) EndSession(ctx context.Context, req *EndSessionReq, opts ...client.Option) (*EndSessionRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EndSession", varargs...)
	ret0, _ := ret[0].(*EndSessionRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndSession indicates an expected call of EndSession.
func (mr *MockAgentServerClientProxyMockRecorder) EndSession(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndSession", reflect.TypeOf((*MockAgentServerClientProxy)(nil).EndSession), varargs...)
}

// QueryKnowledgeGapList mocks base method.
func (m *MockAgentServerClientProxy) QueryKnowledgeGapList(ctx context.Context, req *QueryKnowledgeGapListReq, opts ...client.Option) (*QueryKnowledgeGapListRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryKnowledgeGapList", varargs...)
	ret0, _ := ret[0].(*QueryKnowledgeGapListRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryKnowledgeGapList indicates an expected call of QueryKnowledgeGapList.
func (mr *MockAgentServerClientProxyMockRecorder) QueryKnowledgeGapList(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryKnowledgeGapList", reflect.TypeOf((*MockAgentServerClientProxy)(nil).QueryKnowledgeGapList), varargs...)
}

// QuerySocraticHistory mocks base method.
func (m *MockAgentServerClientProxy) QuerySocraticHistory(ctx context.Context, req *QuerySocraticHistoryReq, opts ...client.Option) (*QuerySocraticHistoryRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QuerySocraticHistory", varargs...)
	ret0, _ := ret[0].(*QuerySocraticHistoryRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuerySocraticHistory indicates an expected call of QuerySocraticHistory.
func (mr *MockAgentServerClientProxyMockRecorder) QuerySocraticHistory(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySocraticHistory", reflect.TypeOf((*MockAgentServerClientProxy)(nil).QuerySocraticHistory), varargs...)
}

// QuerySocraticSession mocks base method.
func (m *MockAgentServerClientProxy) QuerySocraticSession(ctx context.Context, req *QuerySocraticSessionReq, opts ...client.Option) (*QuerySocraticSessionRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QuerySocraticSession", varargs...)
	ret0, _ := ret[0].(*QuerySocraticSessionRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QuerySocraticSession indicates an expected call of QuerySocraticSession.
func (mr *MockAgentServerClientProxyMockRecorder) QuerySocraticSession(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySocraticSession", reflect.TypeOf((*MockAgentServerClientProxy)(nil).QuerySocraticSession), varargs...)
}

// QueryTeacherDashboard mocks base method.
func (m *MockAgentServerClientProxy) QueryTeacherDashboard(ctx context.Context, req *QueryTeacherDashboardReq, opts ...client.Option) (*QueryTeacherDashboardRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryTeacherDashboard", varargs...)
	ret0, _ := ret[0].(*QueryTeacherDashboardRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryTeacherDashboard indicates an expected call of QueryTeacherDashboard.
func (mr *MockAgentServerClientProxyMockRecorder) QueryTeacherDashboard(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryTeacherDashboard", reflect.TypeOf((*MockAgentServerClientProxy)(nil).QueryTeacherDashboard), varargs...)
}

// QueryTeacherKnowledgeGapList mocks base method.
func (m *MockAgentServerClientProxy) QueryTeacherKnowledgeGapList(ctx context.Context, req *QueryTeacherKnowledgeGapListReq, opts ...client.Option) (*QueryTeacherKnowledgeGapListRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryTeacherKnowledgeGapList", varargs...)
	ret0, _ := ret[0].(*QueryTeacherKnowledgeGapListRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryTeacherKnowledgeGapList indicates an expected call of QueryTeacherKnowledgeGapList.
func (mr *MockAgentServerClientProxyMockRecorder) QueryTeacherKnowledgeGapList(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryTeacherKnowledgeGapList", reflect.TypeOf((*MockAgentServerClientProxy)(nil).QueryTeacherKnowledgeGapList), varargs...)
}

// QueryTeacherSessionDetail mocks base method.
func (m *MockAgentServerClientProxy) QueryTeacherSessionDetail(ctx context.Context, req *QueryTeacherSessionDetailReq, opts ...client.Option) (*QueryTeacherSessionDetailRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryTeacherSessionDetail", varargs...)
	ret0, _ := ret[0].(*QueryTeacherSessionDetailRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryTeacherSessionDetail indicates an expected call of QueryTeacherSessionDetail.
func (mr *MockAgentServerClientProxyMockRecorder) QueryTeacherSessionDetail(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryTeacherSessionDetail", reflect.TypeOf((*MockAgentServerClientProxy)(nil).QueryTeacherSessionDetail), varargs...)
}

// QueryTeacherSessionList mocks base method.
func (m *MockAgentServerClientProxy) QueryTeacherSessionList(ctx context.Context, req *QueryTeacherSessionListReq, opts ...client.Option) (*QueryTeacherSessionListRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryTeacherSessionList", varargs...)
	ret0, _ := ret[0].(*QueryTeacherSessionListRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryTeacherSessionList indicates an expected call of QueryTeacherSessionList.
func (mr *MockAgentServerClientProxyMockRecorder) QueryTeacherSessionList(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryTeacherSessionList", reflect.TypeOf((*MockAgentServerClientProxy)(nil).QueryTeacherSessionList), varargs...)
}

// SocraticAsk mocks base method.
func (m *MockAgentServerClientProxy) SocraticAsk(ctx context.Context, req *SocraticAskReq, opts ...client.Option) (*SocraticAskRsp, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SocraticAsk", varargs...)
	ret0, _ := ret[0].(*SocraticAskRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SocraticAsk indicates an expected call of SocraticAsk.
func (mr *MockAgentServerClientProxyMockRecorder) SocraticAsk(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SocraticAsk", reflect.TypeOf((*MockAgentServerClientProxy)(nil).SocraticAsk), varargs...)
}

// SocraticAskStream mocks base method.
func (m *MockAgentServerClientProxy) SocraticAskStream(ctx context.Context, req *SocraticAskReq, opts ...client.Option) (AgentServer_SocraticAskStreamClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SocraticAskStream", varargs...)
	ret0, _ := ret[0].(AgentServer_SocraticAskStreamClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SocraticAskStream indicates an expected call of SocraticAskStream.
func (mr *MockAgentServerClientProxyMockRecorder) SocraticAskStream(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SocraticAskStream", reflect.TypeOf((*MockAgentServerClientProxy)(nil).SocraticAskStream), varargs...)
}

// MockAgentServer_SocraticAskStreamClient is a mock of AgentServer_SocraticAskStreamClient interface.
type MockAgentServer_SocraticAskStreamClient struct {
	ctrl     *gomock.Controller
	recorder *MockAgentServer_SocraticAskStreamClientMockRecorder
}

// MockAgentServer_SocraticAskStreamClientMockRecorder is the mock recorder for MockAgentServer_SocraticAskStreamClient.
type MockAgentServer_SocraticAskStreamClientMockRecorder struct {
	mock *MockAgentServer_SocraticAskStreamClient
}

// NewMockAgentServer_SocraticAskStreamClient creates a new mock instance.
func NewMockAgentServer_SocraticAskStreamClient(ctrl *gomock.Controller) *MockAgentServer_SocraticAskStreamClient {
	mock := &MockAgentServer_SocraticAskStreamClient{ctrl: ctrl}
	mock.recorder = &MockAgentServer_SocraticAskStreamClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentServer_SocraticAskStreamClient) EXPECT() *MockAgentServer_SocraticAskStreamClientMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockAgentServer_SocraticAskStreamClient) ISGOMOCK() struct{} {
	return struct{}{}
}

// CloseSend mocks base method.
func (m *MockAgentServer_SocraticAskStreamClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockAgentServer_SocraticAskStreamClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockAgentServer_SocraticAskStreamClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockAgentServer_SocraticAskStreamClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockAgentServer_SocraticAskStreamClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockAgentServer_SocraticAskStreamClient)(nil).Context))
}

// Recv mocks base method.
func (m *MockAgentServer_SocraticAskStreamClient) Recv() (*SocraticAskChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*SocraticAskChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockAgentServer_SocraticAskStreamClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockAgentServer_SocraticAskStreamClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockAgentServer_SocraticAskStreamClient) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockAgentServer_SocraticAskStreamClientMockRecorder) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockAgentServer_SocraticAskStreamClient)(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockAgentServer_SocraticAskStreamClient) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockAgentServer_SocraticAskStreamClientMockRecorder) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockAgentServer_SocraticAskStreamClient)(nil).SendMsg), m)
}
