// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: agent.proto

package agent

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SocraticAskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemID     int32                  `protobuf:"varint,1,opt,name=problemID,proto3" json:"problemID,omitempty"`   // 题目编号
	UserID        int32                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`         // 学生编号
	Question      string                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`      // 学生的提问或对上一轮引导的回答
	SolutionID    int32                  `protobuf:"varint,4,opt,name=solutionID,proto3" json:"solutionID,omitempty"` // 提交编号；0 表示由服务端选择该用户在这道题上的最新提交
	SessionID     string                 `protobuf:"bytes,5,opt,name=sessionID,proto3" json:"sessionID,omitempty"`    // 会话编号；为空表示继续 userID + problemID 对应的当前会话
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocraticAskReq) Reset() {
	*x = SocraticAskReq{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocraticAskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocraticAskReq) ProtoMessage() {}

func (x *SocraticAskReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocraticAskReq.ProtoReflect.Descriptor instead.
func (*SocraticAskReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *SocraticAskReq) GetProblemID() int32 {
	if x != nil {
		return x.ProblemID
	}
	return 0
}

func (x *SocraticAskReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SocraticAskReq) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *SocraticAskReq) GetSolutionID() int32 {
	if x != nil {
		return x.SolutionID
	}
	return 0
}

func (x *SocraticAskReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type SocraticAskRsp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Message         string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                 // 返回信息
	Code            int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`                      // 返回码
	Session         *SocraticSession       `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`                 // 会话状态
	StudentMessage  *SocraticMessage       `protobuf:"bytes,4,opt,name=studentMessage,proto3" json:"studentMessage,omitempty"`   // 本轮学生消息
	AgentMessage    *SocraticMessage       `protobuf:"bytes,5,opt,name=agentMessage,proto3" json:"agentMessage,omitempty"`       // 本轮 Agent 回复，回复正文在 content 中
	HintLevel       int32                  `protobuf:"varint,6,opt,name=hintLevel,proto3" json:"hintLevel,omitempty"`            // 当前提示等级，1=间接反问 2=具体提示 3=概念解释
	Strategy        string                 `protobuf:"bytes,7,opt,name=strategy,proto3" json:"strategy,omitempty"`               // 本轮使用的策略
	KnowledgePoints []*KnowledgePoint      `protobuf:"bytes,8,rep,name=knowledgePoints,proto3" json:"knowledgePoints,omitempty"` // 本轮涉及的知识点
	GuardrailPass   int32                  `protobuf:"varint,9,opt,name=guardrailPass,proto3" json:"guardrailPass,omitempty"`    // 安全审查结果，0=失败 1=通过 2=已重写
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SocraticAskRsp) Reset() {
	*x = SocraticAskRsp{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocraticAskRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocraticAskRsp) ProtoMessage() {}

func (x *SocraticAskRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocraticAskRsp.ProtoReflect.Descriptor instead.
func (*SocraticAskRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SocraticAskRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SocraticAskRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SocraticAskRsp) GetSession() *SocraticSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *SocraticAskRsp) GetStudentMessage() *SocraticMessage {
	if x != nil {
		return x.StudentMessage
	}
	return nil
}

func (x *SocraticAskRsp) GetAgentMessage() *SocraticMessage {
	if x != nil {
		return x.AgentMessage
	}
	return nil
}

func (x *SocraticAskRsp) GetHintLevel() int32 {
	if x != nil {
		return x.HintLevel
	}
	return 0
}

func (x *SocraticAskRsp) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *SocraticAskRsp) GetKnowledgePoints() []*KnowledgePoint {
	if x != nil {
		return x.KnowledgePoints
	}
	return nil
}

func (x *SocraticAskRsp) GetGuardrailPass() int32 {
	if x != nil {
		return x.GuardrailPass
	}
	return 0
}

type SocraticAskChunk struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Message         string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                  // 返回信息
	Code            int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`                       // 返回码
	ChunkType       int32                  `protobuf:"varint,3,opt,name=chunkType,proto3" json:"chunkType,omitempty"`             // 0=增量内容 1=最终结果
	Delta           string                 `protobuf:"bytes,4,opt,name=delta,proto3" json:"delta,omitempty"`                      // 增量文本，chunkType=0 时使用
	Finished        bool                   `protobuf:"varint,5,opt,name=finished,proto3" json:"finished,omitempty"`               // 是否结束
	SessionID       string                 `protobuf:"bytes,6,opt,name=sessionID,proto3" json:"sessionID,omitempty"`              // 会话编号
	Turn            int32                  `protobuf:"varint,7,opt,name=turn,proto3" json:"turn,omitempty"`                       // 当前对话轮数
	Strategy        string                 `protobuf:"bytes,8,opt,name=strategy,proto3" json:"strategy,omitempty"`                // Agent 最终使用的策略
	HintLevel       int32                  `protobuf:"varint,9,opt,name=hintLevel,proto3" json:"hintLevel,omitempty"`             // Agent 最终使用的提示等级
	KnowledgePoints []*KnowledgePoint      `protobuf:"bytes,10,rep,name=knowledgePoints,proto3" json:"knowledgePoints,omitempty"` // 本轮涉及的知识点
	AgentMessage    *SocraticMessage       `protobuf:"bytes,11,opt,name=agentMessage,proto3" json:"agentMessage,omitempty"`       // 完整 Agent 回复，chunkType=1 时填充
	GuardrailPass   int32                  `protobuf:"varint,12,opt,name=guardrailPass,proto3" json:"guardrailPass,omitempty"`    // 安全审查结果，0=失败 1=通过 2=已重写
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SocraticAskChunk) Reset() {
	*x = SocraticAskChunk{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocraticAskChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocraticAskChunk) ProtoMessage() {}

func (x *SocraticAskChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocraticAskChunk.ProtoReflect.Descriptor instead.
func (*SocraticAskChunk) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SocraticAskChunk) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SocraticAskChunk) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SocraticAskChunk) GetChunkType() int32 {
	if x != nil {
		return x.ChunkType
	}
	return 0
}

func (x *SocraticAskChunk) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *SocraticAskChunk) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *SocraticAskChunk) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *SocraticAskChunk) GetTurn() int32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *SocraticAskChunk) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *SocraticAskChunk) GetHintLevel() int32 {
	if x != nil {
		return x.HintLevel
	}
	return 0
}

func (x *SocraticAskChunk) GetKnowledgePoints() []*KnowledgePoint {
	if x != nil {
		return x.KnowledgePoints
	}
	return nil
}

func (x *SocraticAskChunk) GetAgentMessage() *SocraticMessage {
	if x != nil {
		return x.AgentMessage
	}
	return nil
}

func (x *SocraticAskChunk) GetGuardrailPass() int32 {
	if x != nil {
		return x.GuardrailPass
	}
	return 0
}

type QuerySocraticSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`       // 学生编号
	ProblemID     int32                  `protobuf:"varint,2,opt,name=problemID,proto3" json:"problemID,omitempty"` // 题目编号
	SessionID     string                 `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`  // 会话编号；为空表示查询当前进行中的会话
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySocraticSessionReq) Reset() {
	*x = QuerySocraticSessionReq{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySocraticSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySocraticSessionReq) ProtoMessage() {}

func (x *QuerySocraticSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySocraticSessionReq.ProtoReflect.Descriptor instead.
func (*QuerySocraticSessionReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *QuerySocraticSessionReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QuerySocraticSessionReq) GetProblemID() int32 {
	if x != nil {
		return x.ProblemID
	}
	return 0
}

func (x *QuerySocraticSessionReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type QuerySocraticSessionRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 返回信息
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 返回码
	Session       *SocraticSession       `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"` // 会话状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySocraticSessionRsp) Reset() {
	*x = QuerySocraticSessionRsp{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySocraticSessionRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySocraticSessionRsp) ProtoMessage() {}

func (x *QuerySocraticSessionRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySocraticSessionRsp.ProtoReflect.Descriptor instead.
func (*QuerySocraticSessionRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *QuerySocraticSessionRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QuerySocraticSessionRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QuerySocraticSessionRsp) GetSession() *SocraticSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type QuerySocraticHistoryReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserID          int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`                   // 学生编号
	ProblemID       int32                  `protobuf:"varint,2,opt,name=problemID,proto3" json:"problemID,omitempty"`             // 题目编号
	SessionID       string                 `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`              // 会话编号；为空表示查询该用户在这道题上的全部会话
	Page            int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`                       // 页码，从 1 开始
	Limit           int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                     // 每页条数
	Roles           []int32                `protobuf:"varint,6,rep,packed,name=roles,proto3" json:"roles,omitempty"`              // 消息角色过滤，0=学生 1=Agent；空表示全部
	StartTime       string                 `protobuf:"bytes,7,opt,name=startTime,proto3" json:"startTime,omitempty"`              // 开始时间，格式 yyyy-MM-dd HH:mm:ss；空表示不限制
	EndTime         string                 `protobuf:"bytes,8,opt,name=endTime,proto3" json:"endTime,omitempty"`                  // 结束时间，格式 yyyy-MM-dd HH:mm:ss；空表示不限制
	IncludeDisabled bool                   `protobuf:"varint,9,opt,name=includeDisabled,proto3" json:"includeDisabled,omitempty"` // 是否包含已删除消息
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QuerySocraticHistoryReq) Reset() {
	*x = QuerySocraticHistoryReq{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySocraticHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySocraticHistoryReq) ProtoMessage() {}

func (x *QuerySocraticHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySocraticHistoryReq.ProtoReflect.Descriptor instead.
func (*QuerySocraticHistoryReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *QuerySocraticHistoryReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QuerySocraticHistoryReq) GetProblemID() int32 {
	if x != nil {
		return x.ProblemID
	}
	return 0
}

func (x *QuerySocraticHistoryReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *QuerySocraticHistoryReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QuerySocraticHistoryReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QuerySocraticHistoryReq) GetRoles() []int32 {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *QuerySocraticHistoryReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *QuerySocraticHistoryReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *QuerySocraticHistoryReq) GetIncludeDisabled() bool {
	if x != nil {
		return x.IncludeDisabled
	}
	return false
}

type QuerySocraticHistoryRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`   // 返回信息
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`        // 返回码
	Messages      []*SocraticMessage     `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"` // 消息列表
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`      // 消息总数
	HasMore       bool                   `protobuf:"varint,5,opt,name=hasMore,proto3" json:"hasMore,omitempty"`  // 是否还有下一页
	Session       *SocraticSession       `protobuf:"bytes,6,opt,name=session,proto3" json:"session,omitempty"`   // 指定会话的状态；跨会话查询时可为空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySocraticHistoryRsp) Reset() {
	*x = QuerySocraticHistoryRsp{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySocraticHistoryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySocraticHistoryRsp) ProtoMessage() {}

func (x *QuerySocraticHistoryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySocraticHistoryRsp.ProtoReflect.Descriptor instead.
func (*QuerySocraticHistoryRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *QuerySocraticHistoryRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QuerySocraticHistoryRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QuerySocraticHistoryRsp) GetMessages() []*SocraticMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *QuerySocraticHistoryRsp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QuerySocraticHistoryRsp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *QuerySocraticHistoryRsp) GetSession() *SocraticSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type EndSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`       // 学生编号
	ProblemID     int32                  `protobuf:"varint,2,opt,name=problemID,proto3" json:"problemID,omitempty"` // 题目编号
	SessionID     string                 `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`  // 会话编号；为空表示结束当前进行中的会话
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`        // 结束原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionReq) Reset() {
	*x = EndSessionReq{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionReq) ProtoMessage() {}

func (x *EndSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionReq.ProtoReflect.Descriptor instead.
func (*EndSessionReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *EndSessionReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *EndSessionReq) GetProblemID() int32 {
	if x != nil {
		return x.ProblemID
	}
	return 0
}

func (x *EndSessionReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *EndSessionReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EndSessionRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 返回信息
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 返回码
	Session       *SocraticSession       `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"` // 结束后的会话状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndSessionRsp) Reset() {
	*x = EndSessionRsp{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndSessionRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndSessionRsp) ProtoMessage() {}

func (x *EndSessionRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndSessionRsp.ProtoReflect.Descriptor instead.
func (*EndSessionRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *EndSessionRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EndSessionRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EndSessionRsp) GetSession() *SocraticSession {
	if x != nil {
		return x.Session
	}
	return nil
}

type SocraticSession struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 会话表主键
	SessionID            string                 `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`                         // 会话唯一标识
	UserID               int32                  `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`                              // 学生编号
	ProblemID            int32                  `protobuf:"varint,4,opt,name=problemID,proto3" json:"problemID,omitempty"`                        // 题目编号
	LatestStrategy       string                 `protobuf:"bytes,5,opt,name=latestStrategy,proto3" json:"latestStrategy,omitempty"`               // 最近一次使用的策略
	KnowledgeGaps        []string               `protobuf:"bytes,6,rep,name=knowledgeGaps,proto3" json:"knowledgeGaps,omitempty"`                 // 已识别的薄弱知识点名称
	HintLevel            int32                  `protobuf:"varint,7,opt,name=hintLevel,proto3" json:"hintLevel,omitempty"`                        // 当前提示等级
	TurnCount            int32                  `protobuf:"varint,8,opt,name=turnCount,proto3" json:"turnCount,omitempty"`                        // 当前对话轮数
	Enable               int32                  `protobuf:"varint,9,opt,name=enable,proto3" json:"enable,omitempty"`                              // 1=进行中 0=已结束
	CreatedTime          string                 `protobuf:"bytes,10,opt,name=createdTime,proto3" json:"createdTime,omitempty"`                    // 创建时间
	UpdatedTime          string                 `protobuf:"bytes,11,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`                    // 最后更新时间
	EffectEvaluated      bool                   `protobuf:"varint,12,opt,name=effectEvaluated,proto3" json:"effectEvaluated,omitempty"`           // 教学效果是否已完成评估
	FinalAC              bool                   `protobuf:"varint,13,opt,name=finalAC,proto3" json:"finalAC,omitempty"`                           // 结束会话后学生最新提交是否通过
	EffectiveGuidance    bool                   `protobuf:"varint,14,opt,name=effectiveGuidance,proto3" json:"effectiveGuidance,omitempty"`       // 本次引导是否达成有效教学效果
	SelfExplanationScore int32                  `protobuf:"varint,15,opt,name=selfExplanationScore,proto3" json:"selfExplanationScore,omitempty"` // 自我解释评分，0-3 分
	HintLevelTrace       []int32                `protobuf:"varint,16,rep,packed,name=hintLevelTrace,proto3" json:"hintLevelTrace,omitempty"`      // Agent 回复的提示等级轨迹
	EvaluatedTime        string                 `protobuf:"bytes,17,opt,name=evaluatedTime,proto3" json:"evaluatedTime,omitempty"`                // 效果评估时间
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SocraticSession) Reset() {
	*x = SocraticSession{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocraticSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocraticSession) ProtoMessage() {}

func (x *SocraticSession) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocraticSession.ProtoReflect.Descriptor instead.
func (*SocraticSession) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *SocraticSession) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SocraticSession) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *SocraticSession) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SocraticSession) GetProblemID() int32 {
	if x != nil {
		return x.ProblemID
	}
	return 0
}

func (x *SocraticSession) GetLatestStrategy() string {
	if x != nil {
		return x.LatestStrategy
	}
	return ""
}

func (x *SocraticSession) GetKnowledgeGaps() []string {
	if x != nil {
		return x.KnowledgeGaps
	}
	return nil
}

func (x *SocraticSession) GetHintLevel() int32 {
	if x != nil {
		return x.HintLevel
	}
	return 0
}

func (x *SocraticSession) GetTurnCount() int32 {
	if x != nil {
		return x.TurnCount
	}
	return 0
}

func (x *SocraticSession) GetEnable() int32 {
	if x != nil {
		return x.Enable
	}
	return 0
}

func (x *SocraticSession) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *SocraticSession) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

func (x *SocraticSession) GetEffectEvaluated() bool {
	if x != nil {
		return x.EffectEvaluated
	}
	return false
}

func (x *SocraticSession) GetFinalAC() bool {
	if x != nil {
		return x.FinalAC
	}
	return false
}

func (x *SocraticSession) GetEffectiveGuidance() bool {
	if x != nil {
		return x.EffectiveGuidance
	}
	return false
}

func (x *SocraticSession) GetSelfExplanationScore() int32 {
	if x != nil {
		return x.SelfExplanationScore
	}
	return 0
}

func (x *SocraticSession) GetHintLevelTrace() []int32 {
	if x != nil {
		return x.HintLevelTrace
	}
	return nil
}

func (x *SocraticSession) GetEvaluatedTime() string {
	if x != nil {
		return x.EvaluatedTime
	}
	return ""
}

type SocraticMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                           // 消息表主键
	SessionID       string                 `protobuf:"bytes,2,opt,name=sessionID,proto3" json:"sessionID,omitempty"`              // 会话唯一标识
	UserID          int32                  `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`                   // 学生编号
	ProblemID       int32                  `protobuf:"varint,4,opt,name=problemID,proto3" json:"problemID,omitempty"`             // 题目编号
	Turn            int32                  `protobuf:"varint,5,opt,name=turn,proto3" json:"turn,omitempty"`                       // 第几轮，从 1 开始
	Role            int32                  `protobuf:"varint,6,opt,name=role,proto3" json:"role,omitempty"`                       // 0=学生提问 1=Agent 回复
	Content         string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`                  // 消息内容
	Strategy        string                 `protobuf:"bytes,8,opt,name=strategy,proto3" json:"strategy,omitempty"`                // 策略，仅 Agent 回复有值
	HintLevel       int32                  `protobuf:"varint,9,opt,name=hintLevel,proto3" json:"hintLevel,omitempty"`             // Agent 回复使用的提示等级
	GuardrailPass   int32                  `protobuf:"varint,10,opt,name=guardrailPass,proto3" json:"guardrailPass,omitempty"`    // 安全审查结果，0=失败 1=通过 2=已重写
	TokenCount      int32                  `protobuf:"varint,11,opt,name=tokenCount,proto3" json:"tokenCount,omitempty"`          // 消息 token 用量
	Enable          int32                  `protobuf:"varint,12,opt,name=enable,proto3" json:"enable,omitempty"`                  // 1=有效 0=已删除
	CreatedTime     string                 `protobuf:"bytes,13,opt,name=createdTime,proto3" json:"createdTime,omitempty"`         // 创建时间
	UpdatedTime     string                 `protobuf:"bytes,14,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`         // 最后更新时间
	KnowledgePoints []*KnowledgePoint      `protobuf:"bytes,15,rep,name=knowledgePoints,proto3" json:"knowledgePoints,omitempty"` // 本轮涉及的知识点
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SocraticMessage) Reset() {
	*x = SocraticMessage{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocraticMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocraticMessage) ProtoMessage() {}

func (x *SocraticMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocraticMessage.ProtoReflect.Descriptor instead.
func (*SocraticMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *SocraticMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SocraticMessage) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *SocraticMessage) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SocraticMessage) GetProblemID() int32 {
	if x != nil {
		return x.ProblemID
	}
	return 0
}

func (x *SocraticMessage) GetTurn() int32 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *SocraticMessage) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *SocraticMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SocraticMessage) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *SocraticMessage) GetHintLevel() int32 {
	if x != nil {
		return x.HintLevel
	}
	return 0
}

func (x *SocraticMessage) GetGuardrailPass() int32 {
	if x != nil {
		return x.GuardrailPass
	}
	return 0
}

func (x *SocraticMessage) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *SocraticMessage) GetEnable() int32 {
	if x != nil {
		return x.Enable
	}
	return 0
}

func (x *SocraticMessage) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *SocraticMessage) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

func (x *SocraticMessage) GetKnowledgePoints() []*KnowledgePoint {
	if x != nil {
		return x.KnowledgePoints
	}
	return nil
}

type KnowledgePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeID   int32                  `protobuf:"varint,1,opt,name=knowledgeID,proto3" json:"knowledgeID,omitempty"` // 知识点编号
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                // 知识点名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgePoint) Reset() {
	*x = KnowledgePoint{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgePoint) ProtoMessage() {}

func (x *KnowledgePoint) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgePoint.ProtoReflect.Descriptor instead.
func (*KnowledgePoint) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *KnowledgePoint) GetKnowledgeID() int32 {
	if x != nil {
		return x.KnowledgeID
	}
	return 0
}

func (x *KnowledgePoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SocraticKnowledgeGap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                      // 薄弱点表主键
	UserID        int32                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`              // 学生编号
	KnowledgeID   int32                  `protobuf:"varint,3,opt,name=knowledgeID,proto3" json:"knowledgeID,omitempty"`    // 知识点编号；0 表示尚未关联
	KnowledgeName string                 `protobuf:"bytes,4,opt,name=knowledgeName,proto3" json:"knowledgeName,omitempty"` // 知识点名称
	ProblemID     int32                  `protobuf:"varint,5,opt,name=problemID,proto3" json:"problemID,omitempty"`        // 首次识别到该薄弱点的题目编号
	Frequency     int32                  `protobuf:"varint,6,opt,name=frequency,proto3" json:"frequency,omitempty"`        // 累计出现次数
	Enable        int32                  `protobuf:"varint,7,opt,name=enable,proto3" json:"enable,omitempty"`              // 1=有效 0=已失效
	CreatedTime   string                 `protobuf:"bytes,8,opt,name=createdTime,proto3" json:"createdTime,omitempty"`     // 首次识别时间
	UpdatedTime   string                 `protobuf:"bytes,9,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`     // 最后更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocraticKnowledgeGap) Reset() {
	*x = SocraticKnowledgeGap{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocraticKnowledgeGap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocraticKnowledgeGap) ProtoMessage() {}

func (x *SocraticKnowledgeGap) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocraticKnowledgeGap.ProtoReflect.Descriptor instead.
func (*SocraticKnowledgeGap) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *SocraticKnowledgeGap) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SocraticKnowledgeGap) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SocraticKnowledgeGap) GetKnowledgeID() int32 {
	if x != nil {
		return x.KnowledgeID
	}
	return 0
}

func (x *SocraticKnowledgeGap) GetKnowledgeName() string {
	if x != nil {
		return x.KnowledgeName
	}
	return ""
}

func (x *SocraticKnowledgeGap) GetProblemID() int32 {
	if x != nil {
		return x.ProblemID
	}
	return 0
}

func (x *SocraticKnowledgeGap) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *SocraticKnowledgeGap) GetEnable() int32 {
	if x != nil {
		return x.Enable
	}
	return 0
}

func (x *SocraticKnowledgeGap) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *SocraticKnowledgeGap) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

type QueryKnowledgeGapListReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserID          int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`                   // 学生编号
	ProblemID       int32                  `protobuf:"varint,2,opt,name=problemID,proto3" json:"problemID,omitempty"`             // 题目编号；0 表示查询全部题目
	Page            int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                       // 页码，从 1 开始
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                     // 每页条数
	IncludeDisabled bool                   `protobuf:"varint,5,opt,name=includeDisabled,proto3" json:"includeDisabled,omitempty"` // 是否包含已失效记录
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryKnowledgeGapListReq) Reset() {
	*x = QueryKnowledgeGapListReq{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKnowledgeGapListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKnowledgeGapListReq) ProtoMessage() {}

func (x *QueryKnowledgeGapListReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKnowledgeGapListReq.ProtoReflect.Descriptor instead.
func (*QueryKnowledgeGapListReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *QueryKnowledgeGapListReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QueryKnowledgeGapListReq) GetProblemID() int32 {
	if x != nil {
		return x.ProblemID
	}
	return 0
}

func (x *QueryKnowledgeGapListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryKnowledgeGapListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryKnowledgeGapListReq) GetIncludeDisabled() bool {
	if x != nil {
		return x.IncludeDisabled
	}
	return false
}

type QueryKnowledgeGapListRsp struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Message       string                  `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`  // 返回信息
	Code          int32                   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`       // 返回码
	Gaps          []*SocraticKnowledgeGap `protobuf:"bytes,3,rep,name=gaps,proto3" json:"gaps,omitempty"`        // 薄弱点列表
	Total         int32                   `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`     // 记录总数
	HasMore       bool                    `protobuf:"varint,5,opt,name=hasMore,proto3" json:"hasMore,omitempty"` // 是否还有下一页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryKnowledgeGapListRsp) Reset() {
	*x = QueryKnowledgeGapListRsp{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKnowledgeGapListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKnowledgeGapListRsp) ProtoMessage() {}

func (x *QueryKnowledgeGapListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKnowledgeGapListRsp.ProtoReflect.Descriptor instead.
func (*QueryKnowledgeGapListRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *QueryKnowledgeGapListRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryKnowledgeGapListRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryKnowledgeGapListRsp) GetGaps() []*SocraticKnowledgeGap {
	if x != nil {
		return x.Gaps
	}
	return nil
}

func (x *QueryKnowledgeGapListRsp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryKnowledgeGapListRsp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type QueryTeacherDashboardReq struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TeacherID            int32                  `protobuf:"varint,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"`                       // 教师编号
	ClassID              int32                  `protobuf:"varint,2,opt,name=classID,proto3" json:"classID,omitempty"`                           // 班级编号；0 表示教师负责的全部班级
	StartTime            string                 `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`                        // 开始时间；空表示不限制
	EndTime              string                 `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`                            // 结束时间；空表示不限制
	TopKnowledgeGapLimit int32                  `protobuf:"varint,5,opt,name=topKnowledgeGapLimit,proto3" json:"topKnowledgeGapLimit,omitempty"` // 高频薄弱点条数，默认 10，0 使用服务端默认值
	RecentSessionLimit   int32                  `protobuf:"varint,6,opt,name=recentSessionLimit,proto3" json:"recentSessionLimit,omitempty"`     // 最近会话条数，默认 10，0 使用服务端默认值
	UserID               int32                  `protobuf:"varint,7,opt,name=userID,proto3" json:"userID,omitempty"`                             // 学生编号；0 表示不限制
	ProblemID            int32                  `protobuf:"varint,8,opt,name=problemID,proto3" json:"problemID,omitempty"`                       // 题目编号；0 表示不限制
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QueryTeacherDashboardReq) Reset() {
	*x = QueryTeacherDashboardReq{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTeacherDashboardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTeacherDashboardReq) ProtoMessage() {}

func (x *QueryTeacherDashboardReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTeacherDashboardReq.ProtoReflect.Descriptor instead.
func (*QueryTeacherDashboardReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *QueryTeacherDashboardReq) GetTeacherID() int32 {
	if x != nil {
		return x.TeacherID
	}
	return 0
}

func (x *QueryTeacherDashboardReq) GetClassID() int32 {
	if x != nil {
		return x.ClassID
	}
	return 0
}

func (x *QueryTeacherDashboardReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *QueryTeacherDashboardReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *QueryTeacherDashboardReq) GetTopKnowledgeGapLimit() int32 {
	if x != nil {
		return x.TopKnowledgeGapLimit
	}
	return 0
}

func (x *QueryTeacherDashboardReq) GetRecentSessionLimit() int32 {
	if x != nil {
		return x.RecentSessionLimit
	}
	return 0
}

func (x *QueryTeacherDashboardReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QueryTeacherDashboardReq) GetProblemID() int32 {
	if x != nil {
		return x.ProblemID
	}
	return 0
}

type QueryTeacherDashboardRsp struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Message       string                   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 返回信息
	Code          int32                    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // 返回码
	Summary       *TeacherDashboardSummary `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"` // 统计概览
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTeacherDashboardRsp) Reset() {
	*x = QueryTeacherDashboardRsp{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTeacherDashboardRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTeacherDashboardRsp) ProtoMessage() {}

func (x *QueryTeacherDashboardRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTeacherDashboardRsp.ProtoReflect.Descriptor instead.
func (*QueryTeacherDashboardRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *QueryTeacherDashboardRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryTeacherDashboardRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryTeacherDashboardRsp) GetSummary() *TeacherDashboardSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type TeacherDashboardSummary struct {
	state                       protoimpl.MessageState       `protogen:"open.v1"`
	TeacherID                   int32                        `protobuf:"varint,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"`                                       // 教师编号
	ClassID                     int32                        `protobuf:"varint,2,opt,name=classID,proto3" json:"classID,omitempty"`                                           // 班级编号
	StudentCount                int32                        `protobuf:"varint,3,opt,name=studentCount,proto3" json:"studentCount,omitempty"`                                 // 参与学生数
	ActiveSessionCount          int32                        `protobuf:"varint,4,opt,name=activeSessionCount,proto3" json:"activeSessionCount,omitempty"`                     // 进行中会话数
	TotalSessionCount           int32                        `protobuf:"varint,5,opt,name=totalSessionCount,proto3" json:"totalSessionCount,omitempty"`                       // 会话总数
	TotalMessageCount           int32                        `protobuf:"varint,6,opt,name=totalMessageCount,proto3" json:"totalMessageCount,omitempty"`                       // 消息总数
	KnowledgeGapCount           int32                        `protobuf:"varint,7,opt,name=knowledgeGapCount,proto3" json:"knowledgeGapCount,omitempty"`                       // 薄弱点记录总数
	TopKnowledgeGaps            []*TeacherKnowledgeGapItem   `protobuf:"bytes,8,rep,name=topKnowledgeGaps,proto3" json:"topKnowledgeGaps,omitempty"`                          // 高频薄弱点
	RecentSessions              []*TeacherSessionItem        `protobuf:"bytes,9,rep,name=recentSessions,proto3" json:"recentSessions,omitempty"`                              // 最近会话
	EvaluatedSessionCount       int32                        `protobuf:"varint,10,opt,name=evaluatedSessionCount,proto3" json:"evaluatedSessionCount,omitempty"`              // 已评估教学效果的会话数
	FinalACSessionCount         int32                        `protobuf:"varint,11,opt,name=finalACSessionCount,proto3" json:"finalACSessionCount,omitempty"`                  // 会话结束后最终 AC 的会话数
	EffectiveSessionCount       int32                        `protobuf:"varint,12,opt,name=effectiveSessionCount,proto3" json:"effectiveSessionCount,omitempty"`              // 判定为有效引导的会话数
	FinalACRate                 float64                      `protobuf:"fixed64,13,opt,name=finalACRate,proto3" json:"finalACRate,omitempty"`                                 // 最终 AC 比例
	EffectiveGuidanceRate       float64                      `protobuf:"fixed64,14,opt,name=effectiveGuidanceRate,proto3" json:"effectiveGuidanceRate,omitempty"`             // 有效引导率
	AverageTurnCount            float64                      `protobuf:"fixed64,15,opt,name=averageTurnCount,proto3" json:"averageTurnCount,omitempty"`                       // 已评估会话平均轮次
	AverageSelfExplanationScore float64                      `protobuf:"fixed64,16,opt,name=averageSelfExplanationScore,proto3" json:"averageSelfExplanationScore,omitempty"` // 平均自我解释得分
	GrowthTrends                []*TeacherKnowledgeTrendItem `protobuf:"bytes,17,rep,name=growthTrends,proto3" json:"growthTrends,omitempty"`                                 // 最近画像成长趋势
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *TeacherDashboardSummary) Reset() {
	*x = TeacherDashboardSummary{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherDashboardSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherDashboardSummary) ProtoMessage() {}

func (x *TeacherDashboardSummary) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherDashboardSummary.ProtoReflect.Descriptor instead.
func (*TeacherDashboardSummary) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *TeacherDashboardSummary) GetTeacherID() int32 {
	if x != nil {
		return x.TeacherID
	}
	return 0
}

func (x *TeacherDashboardSummary) GetClassID() int32 {
	if x != nil {
		return x.ClassID
	}
	return 0
}

func (x *TeacherDashboardSummary) GetStudentCount() int32 {
	if x != nil {
		return x.StudentCount
	}
	return 0
}

func (x *TeacherDashboardSummary) GetActiveSessionCount() int32 {
	if x != nil {
		return x.ActiveSessionCount
	}
	return 0
}

func (x *TeacherDashboardSummary) GetTotalSessionCount() int32 {
	if x != nil {
		return x.TotalSessionCount
	}
	return 0
}

func (x *TeacherDashboardSummary) GetTotalMessageCount() int32 {
	if x != nil {
		return x.TotalMessageCount
	}
	return 0
}

func (x *TeacherDashboardSummary) GetKnowledgeGapCount() int32 {
	if x != nil {
		return x.KnowledgeGapCount
	}
	return 0
}

func (x *TeacherDashboardSummary) GetTopKnowledgeGaps() []*TeacherKnowledgeGapItem {
	if x != nil {
		return x.TopKnowledgeGaps
	}
	return nil
}

func (x *TeacherDashboardSummary) GetRecentSessions() []*TeacherSessionItem {
	if x != nil {
		return x.RecentSessions
	}
	return nil
}

func (x *TeacherDashboardSummary) GetEvaluatedSessionCount() int32 {
	if x != nil {
		return x.EvaluatedSessionCount
	}
	return 0
}

func (x *TeacherDashboardSummary) GetFinalACSessionCount() int32 {
	if x != nil {
		return x.FinalACSessionCount
	}
	return 0
}

func (x *TeacherDashboardSummary) GetEffectiveSessionCount() int32 {
	if x != nil {
		return x.EffectiveSessionCount
	}
	return 0
}

func (x *TeacherDashboardSummary) GetFinalACRate() float64 {
	if x != nil {
		return x.FinalACRate
	}
	return 0
}

func (x *TeacherDashboardSummary) GetEffectiveGuidanceRate() float64 {
	if x != nil {
		return x.EffectiveGuidanceRate
	}
	return 0
}

func (x *TeacherDashboardSummary) GetAverageTurnCount() float64 {
	if x != nil {
		return x.AverageTurnCount
	}
	return 0
}

func (x *TeacherDashboardSummary) GetAverageSelfExplanationScore() float64 {
	if x != nil {
		return x.AverageSelfExplanationScore
	}
	return 0
}

func (x *TeacherDashboardSummary) GetGrowthTrends() []*TeacherKnowledgeTrendItem {
	if x != nil {
		return x.GrowthTrends
	}
	return nil
}

type QueryTeacherSessionListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherID     int32                  `protobuf:"varint,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"` // 教师编号
	ClassID       int32                  `protobuf:"varint,2,opt,name=classID,proto3" json:"classID,omitempty"`     // 班级编号；0 表示不限制
	UserID        int32                  `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`       // 学生编号；0 表示不限制
	ProblemID     int32                  `protobuf:"varint,4,opt,name=problemID,proto3" json:"problemID,omitempty"` // 题目编号；0 表示不限制
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`       // 会话状态，1=进行中 0=已结束；-1 表示全部
	Keyword       string                 `protobuf:"bytes,6,opt,name=keyword,proto3" json:"keyword,omitempty"`      // 学生姓名、学号、题目名称或内容关键词
	StartTime     string                 `protobuf:"bytes,7,opt,name=startTime,proto3" json:"startTime,omitempty"`  // 开始时间
	EndTime       string                 `protobuf:"bytes,8,opt,name=endTime,proto3" json:"endTime,omitempty"`      // 结束时间
	Page          int32                  `protobuf:"varint,9,opt,name=page,proto3" json:"page,omitempty"`           // 页码，从 1 开始
	Limit         int32                  `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`        // 每页条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTeacherSessionListReq) Reset() {
	*x = QueryTeacherSessionListReq{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTeacherSessionListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTeacherSessionListReq) ProtoMessage() {}

func (x *QueryTeacherSessionListReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTeacherSessionListReq.ProtoReflect.Descriptor instead.
func (*QueryTeacherSessionListReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *QueryTeacherSessionListReq) GetTeacherID() int32 {
	if x != nil {
		return x.TeacherID
	}
	return 0
}

func (x *QueryTeacherSessionListReq) GetClassID() int32 {
	if x != nil {
		return x.ClassID
	}
	return 0
}

func (x *QueryTeacherSessionListReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QueryTeacherSessionListReq) GetProblemID() int32 {
	if x != nil {
		return x.ProblemID
	}
	return 0
}

func (x *QueryTeacherSessionListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *QueryTeacherSessionListReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *QueryTeacherSessionListReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *QueryTeacherSessionListReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *QueryTeacherSessionListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryTeacherSessionListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryTeacherSessionListRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`   // 返回信息
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`        // 返回码
	Sessions      []*TeacherSessionItem  `protobuf:"bytes,3,rep,name=sessions,proto3" json:"sessions,omitempty"` // 会话列表
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`      // 会话总数
	HasMore       bool                   `protobuf:"varint,5,opt,name=hasMore,proto3" json:"hasMore,omitempty"`  // 是否还有下一页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTeacherSessionListRsp) Reset() {
	*x = QueryTeacherSessionListRsp{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTeacherSessionListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTeacherSessionListRsp) ProtoMessage() {}

func (x *QueryTeacherSessionListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTeacherSessionListRsp.ProtoReflect.Descriptor instead.
func (*QueryTeacherSessionListRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *QueryTeacherSessionListRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryTeacherSessionListRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryTeacherSessionListRsp) GetSessions() []*TeacherSessionItem {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *QueryTeacherSessionListRsp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryTeacherSessionListRsp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type TeacherSessionItem struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Session              *SocraticSession       `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`                             // 会话基础信息
	StudentName          string                 `protobuf:"bytes,2,opt,name=studentName,proto3" json:"studentName,omitempty"`                     // 学生姓名
	StudentNumber        string                 `protobuf:"bytes,3,opt,name=studentNumber,proto3" json:"studentNumber,omitempty"`                 // 学生学号
	ProblemName          string                 `protobuf:"bytes,4,opt,name=problemName,proto3" json:"problemName,omitempty"`                     // 题目名称
	LastMessageTime      string                 `protobuf:"bytes,5,opt,name=lastMessageTime,proto3" json:"lastMessageTime,omitempty"`             // 最后一条消息时间
	LastMessagePreview   string                 `protobuf:"bytes,6,opt,name=lastMessagePreview,proto3" json:"lastMessagePreview,omitempty"`       // 最后一条消息摘要，前端截断展示
	EffectEvaluated      bool                   `protobuf:"varint,7,opt,name=effectEvaluated,proto3" json:"effectEvaluated,omitempty"`            // 教学效果是否已完成评估
	FinalAC              bool                   `protobuf:"varint,8,opt,name=finalAC,proto3" json:"finalAC,omitempty"`                            // 结束会话后学生最新提交是否通过
	EffectiveGuidance    bool                   `protobuf:"varint,9,opt,name=effectiveGuidance,proto3" json:"effectiveGuidance,omitempty"`        // 本次引导是否达成有效教学效果
	SelfExplanationScore int32                  `protobuf:"varint,10,opt,name=selfExplanationScore,proto3" json:"selfExplanationScore,omitempty"` // 自我解释评分，0-3 分
	HintLevelTrace       []int32                `protobuf:"varint,11,rep,packed,name=hintLevelTrace,proto3" json:"hintLevelTrace,omitempty"`      // Agent 回复的提示等级轨迹
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TeacherSessionItem) Reset() {
	*x = TeacherSessionItem{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherSessionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherSessionItem) ProtoMessage() {}

func (x *TeacherSessionItem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherSessionItem.ProtoReflect.Descriptor instead.
func (*TeacherSessionItem) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *TeacherSessionItem) GetSession() *SocraticSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *TeacherSessionItem) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *TeacherSessionItem) GetStudentNumber() string {
	if x != nil {
		return x.StudentNumber
	}
	return ""
}

func (x *TeacherSessionItem) GetProblemName() string {
	if x != nil {
		return x.ProblemName
	}
	return ""
}

func (x *TeacherSessionItem) GetLastMessageTime() string {
	if x != nil {
		return x.LastMessageTime
	}
	return ""
}

func (x *TeacherSessionItem) GetLastMessagePreview() string {
	if x != nil {
		return x.LastMessagePreview
	}
	return ""
}

func (x *TeacherSessionItem) GetEffectEvaluated() bool {
	if x != nil {
		return x.EffectEvaluated
	}
	return false
}

func (x *TeacherSessionItem) GetFinalAC() bool {
	if x != nil {
		return x.FinalAC
	}
	return false
}

func (x *TeacherSessionItem) GetEffectiveGuidance() bool {
	if x != nil {
		return x.EffectiveGuidance
	}
	return false
}

func (x *TeacherSessionItem) GetSelfExplanationScore() int32 {
	if x != nil {
		return x.SelfExplanationScore
	}
	return 0
}

func (x *TeacherSessionItem) GetHintLevelTrace() []int32 {
	if x != nil {
		return x.HintLevelTrace
	}
	return nil
}

type TeacherKnowledgeTrendItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StatDate        string                 `protobuf:"bytes,1,opt,name=statDate,proto3" json:"statDate,omitempty"`                // 统计日期，格式 YYYY-MM-DD
	KnowledgeName   string                 `protobuf:"bytes,2,opt,name=knowledgeName,proto3" json:"knowledgeName,omitempty"`      // 知识点名称
	OccurrenceCount int32                  `protobuf:"varint,3,opt,name=occurrenceCount,proto3" json:"occurrenceCount,omitempty"` // 当日出现次数
	StudentCount    int32                  `protobuf:"varint,4,opt,name=studentCount,proto3" json:"studentCount,omitempty"`       // 当日覆盖学生数
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TeacherKnowledgeTrendItem) Reset() {
	*x = TeacherKnowledgeTrendItem{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherKnowledgeTrendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherKnowledgeTrendItem) ProtoMessage() {}

func (x *TeacherKnowledgeTrendItem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherKnowledgeTrendItem.ProtoReflect.Descriptor instead.
func (*TeacherKnowledgeTrendItem) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *TeacherKnowledgeTrendItem) GetStatDate() string {
	if x != nil {
		return x.StatDate
	}
	return ""
}

func (x *TeacherKnowledgeTrendItem) GetKnowledgeName() string {
	if x != nil {
		return x.KnowledgeName
	}
	return ""
}

func (x *TeacherKnowledgeTrendItem) GetOccurrenceCount() int32 {
	if x != nil {
		return x.OccurrenceCount
	}
	return 0
}

func (x *TeacherKnowledgeTrendItem) GetStudentCount() int32 {
	if x != nil {
		return x.StudentCount
	}
	return 0
}

type QueryTeacherSessionDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherID     int32                  `protobuf:"varint,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"` // 教师编号
	ClassID       int32                  `protobuf:"varint,2,opt,name=classID,proto3" json:"classID,omitempty"`     // 班级编号，用于教师权限校验
	SessionID     string                 `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`  // 会话编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTeacherSessionDetailReq) Reset() {
	*x = QueryTeacherSessionDetailReq{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTeacherSessionDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTeacherSessionDetailReq) ProtoMessage() {}

func (x *QueryTeacherSessionDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTeacherSessionDetailReq.ProtoReflect.Descriptor instead.
func (*QueryTeacherSessionDetailReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *QueryTeacherSessionDetailReq) GetTeacherID() int32 {
	if x != nil {
		return x.TeacherID
	}
	return 0
}

func (x *QueryTeacherSessionDetailReq) GetClassID() int32 {
	if x != nil {
		return x.ClassID
	}
	return 0
}

func (x *QueryTeacherSessionDetailReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type QueryTeacherSessionDetailRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`   // 返回信息
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`        // 返回码
	Session       *SocraticSession       `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`   // 会话状态
	Messages      []*SocraticMessage     `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"` // 会话内消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTeacherSessionDetailRsp) Reset() {
	*x = QueryTeacherSessionDetailRsp{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTeacherSessionDetailRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTeacherSessionDetailRsp) ProtoMessage() {}

func (x *QueryTeacherSessionDetailRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTeacherSessionDetailRsp.ProtoReflect.Descriptor instead.
func (*QueryTeacherSessionDetailRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *QueryTeacherSessionDetailRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryTeacherSessionDetailRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryTeacherSessionDetailRsp) GetSession() *SocraticSession {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *QueryTeacherSessionDetailRsp) GetMessages() []*SocraticMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type QueryTeacherKnowledgeGapListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherID     int32                  `protobuf:"varint,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"`     // 教师编号
	ClassID       int32                  `protobuf:"varint,2,opt,name=classID,proto3" json:"classID,omitempty"`         // 班级编号；0 表示不限制
	UserID        int32                  `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`           // 学生编号；0 表示不限制
	ProblemID     int32                  `protobuf:"varint,4,opt,name=problemID,proto3" json:"problemID,omitempty"`     // 题目编号；0 表示不限制
	KnowledgeID   int32                  `protobuf:"varint,5,opt,name=knowledgeID,proto3" json:"knowledgeID,omitempty"` // 知识点编号；0 表示不限制
	StartTime     string                 `protobuf:"bytes,6,opt,name=startTime,proto3" json:"startTime,omitempty"`      // 开始时间
	EndTime       string                 `protobuf:"bytes,7,opt,name=endTime,proto3" json:"endTime,omitempty"`          // 结束时间
	Page          int32                  `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`               // 页码，从 1 开始
	Limit         int32                  `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"`             // 每页条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTeacherKnowledgeGapListReq) Reset() {
	*x = QueryTeacherKnowledgeGapListReq{}
	mi := &file_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTeacherKnowledgeGapListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTeacherKnowledgeGapListReq) ProtoMessage() {}

func (x *QueryTeacherKnowledgeGapListReq) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTeacherKnowledgeGapListReq.ProtoReflect.Descriptor instead.
func (*QueryTeacherKnowledgeGapListReq) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

func (x *QueryTeacherKnowledgeGapListReq) GetTeacherID() int32 {
	if x != nil {
		return x.TeacherID
	}
	return 0
}

func (x *QueryTeacherKnowledgeGapListReq) GetClassID() int32 {
	if x != nil {
		return x.ClassID
	}
	return 0
}

func (x *QueryTeacherKnowledgeGapListReq) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *QueryTeacherKnowledgeGapListReq) GetProblemID() int32 {
	if x != nil {
		return x.ProblemID
	}
	return 0
}

func (x *QueryTeacherKnowledgeGapListReq) GetKnowledgeID() int32 {
	if x != nil {
		return x.KnowledgeID
	}
	return 0
}

func (x *QueryTeacherKnowledgeGapListReq) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *QueryTeacherKnowledgeGapListReq) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *QueryTeacherKnowledgeGapListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *QueryTeacherKnowledgeGapListReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type QueryTeacherKnowledgeGapListRsp struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Message       string                     `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`  // 返回信息
	Code          int32                      `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`       // 返回码
	Items         []*TeacherKnowledgeGapItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`      // 薄弱点列表
	Total         int32                      `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`     // 记录总数
	HasMore       bool                       `protobuf:"varint,5,opt,name=hasMore,proto3" json:"hasMore,omitempty"` // 是否还有下一页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTeacherKnowledgeGapListRsp) Reset() {
	*x = QueryTeacherKnowledgeGapListRsp{}
	mi := &file_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTeacherKnowledgeGapListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTeacherKnowledgeGapListRsp) ProtoMessage() {}

func (x *QueryTeacherKnowledgeGapListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTeacherKnowledgeGapListRsp.ProtoReflect.Descriptor instead.
func (*QueryTeacherKnowledgeGapListRsp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{25}
}

func (x *QueryTeacherKnowledgeGapListRsp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryTeacherKnowledgeGapListRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryTeacherKnowledgeGapListRsp) GetItems() []*TeacherKnowledgeGapItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *QueryTeacherKnowledgeGapListRsp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryTeacherKnowledgeGapListRsp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type TeacherKnowledgeGapItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gap           *SocraticKnowledgeGap  `protobuf:"bytes,1,opt,name=gap,proto3" json:"gap,omitempty"`                     // 薄弱点基础信息
	StudentName   string                 `protobuf:"bytes,2,opt,name=studentName,proto3" json:"studentName,omitempty"`     // 学生姓名
	StudentNumber string                 `protobuf:"bytes,3,opt,name=studentNumber,proto3" json:"studentNumber,omitempty"` // 学生学号
	ProblemName   string                 `protobuf:"bytes,4,opt,name=problemName,proto3" json:"problemName,omitempty"`     // 题目名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeacherKnowledgeGapItem) Reset() {
	*x = TeacherKnowledgeGapItem{}
	mi := &file_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherKnowledgeGapItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherKnowledgeGapItem) ProtoMessage() {}

func (x *TeacherKnowledgeGapItem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherKnowledgeGapItem.ProtoReflect.Descriptor instead.
func (*TeacherKnowledgeGapItem) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{26}
}

func (x *TeacherKnowledgeGapItem) GetGap() *SocraticKnowledgeGap {
	if x != nil {
		return x.Gap
	}
	return nil
}

func (x *TeacherKnowledgeGapItem) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *TeacherKnowledgeGapItem) GetStudentNumber() string {
	if x != nil {
		return x.StudentNumber
	}
	return ""
}

func (x *TeacherKnowledgeGapItem) GetProblemName() string {
	if x != nil {
		return x.ProblemName
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\boj.agent\"\xa0\x01\n" +
	"\x0eSocraticAskReq\x12\x1c\n" +
	"\tproblemID\x18\x01 \x01(\x05R\tproblemID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x05R\x06userID\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\tR\bquestion\x12\x1e\n" +
	"\n" +
	"solutionID\x18\x04 \x01(\x05R\n" +
	"solutionID\x12\x1c\n" +
	"\tsessionID\x18\x05 \x01(\tR\tsessionID\"\x99\x03\n" +
	"\x0eSocraticAskRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x123\n" +
	"\asession\x18\x03 \x01(\v2\x19.oj.agent.SocraticSessionR\asession\x12A\n" +
	"\x0estudentMessage\x18\x04 \x01(\v2\x19.oj.agent.SocraticMessageR\x0estudentMessage\x12=\n" +
	"\fagentMessage\x18\x05 \x01(\v2\x19.oj.agent.SocraticMessageR\fagentMessage\x12\x1c\n" +
	"\thintLevel\x18\x06 \x01(\x05R\thintLevel\x12\x1a\n" +
	"\bstrategy\x18\a \x01(\tR\bstrategy\x12B\n" +
	"\x0fknowledgePoints\x18\b \x03(\v2\x18.oj.agent.KnowledgePointR\x0fknowledgePoints\x12$\n" +
	"\rguardrailPass\x18\t \x01(\x05R\rguardrailPass\"\xa5\x03\n" +
	"\x10SocraticAskChunk\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x1c\n" +
	"\tchunkType\x18\x03 \x01(\x05R\tchunkType\x12\x14\n" +
	"\x05delta\x18\x04 \x01(\tR\x05delta\x12\x1a\n" +
	"\bfinished\x18\x05 \x01(\bR\bfinished\x12\x1c\n" +
	"\tsessionID\x18\x06 \x01(\tR\tsessionID\x12\x12\n" +
	"\x04turn\x18\a \x01(\x05R\x04turn\x12\x1a\n" +
	"\bstrategy\x18\b \x01(\tR\bstrategy\x12\x1c\n" +
	"\thintLevel\x18\t \x01(\x05R\thintLevel\x12B\n" +
	"\x0fknowledgePoints\x18\n" +
	" \x03(\v2\x18.oj.agent.KnowledgePointR\x0fknowledgePoints\x12=\n" +
	"\fagentMessage\x18\v \x01(\v2\x19.oj.agent.SocraticMessageR\fagentMessage\x12$\n" +
	"\rguardrailPass\x18\f \x01(\x05R\rguardrailPass\"m\n" +
	"\x17QuerySocraticSessionReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x1c\n" +
	"\tproblemID\x18\x02 \x01(\x05R\tproblemID\x12\x1c\n" +
	"\tsessionID\x18\x03 \x01(\tR\tsessionID\"|\n" +
	"\x17QuerySocraticSessionRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x123\n" +
	"\asession\x18\x03 \x01(\v2\x19.oj.agent.SocraticSessionR\asession\"\x8f\x02\n" +
	"\x17QuerySocraticHistoryReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x1c\n" +
	"\tproblemID\x18\x02 \x01(\x05R\tproblemID\x12\x1c\n" +
	"\tsessionID\x18\x03 \x01(\tR\tsessionID\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\x05R\x05roles\x12\x1c\n" +
	"\tstartTime\x18\a \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\b \x01(\tR\aendTime\x12(\n" +
	"\x0fincludeDisabled\x18\t \x01(\bR\x0fincludeDisabled\"\xe3\x01\n" +
	"\x17QuerySocraticHistoryRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x125\n" +
	"\bmessages\x18\x03 \x03(\v2\x19.oj.agent.SocraticMessageR\bmessages\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x18\n" +
	"\ahasMore\x18\x05 \x01(\bR\ahasMore\x123\n" +
	"\asession\x18\x06 \x01(\v2\x19.oj.agent.SocraticSessionR\asession\"{\n" +
	"\rEndSessionReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x1c\n" +
	"\tproblemID\x18\x02 \x01(\x05R\tproblemID\x12\x1c\n" +
	"\tsessionID\x18\x03 \x01(\tR\tsessionID\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"r\n" +
	"\rEndSessionRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x123\n" +
	"\asession\x18\x03 \x01(\v2\x19.oj.agent.SocraticSessionR\asession\"\xcf\x04\n" +
	"\x0fSocraticSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tsessionID\x18\x02 \x01(\tR\tsessionID\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\x05R\x06userID\x12\x1c\n" +
	"\tproblemID\x18\x04 \x01(\x05R\tproblemID\x12&\n" +
	"\x0elatestStrategy\x18\x05 \x01(\tR\x0elatestStrategy\x12$\n" +
	"\rknowledgeGaps\x18\x06 \x03(\tR\rknowledgeGaps\x12\x1c\n" +
	"\thintLevel\x18\a \x01(\x05R\thintLevel\x12\x1c\n" +
	"\tturnCount\x18\b \x01(\x05R\tturnCount\x12\x16\n" +
	"\x06enable\x18\t \x01(\x05R\x06enable\x12 \n" +
	"\vcreatedTime\x18\n" +
	" \x01(\tR\vcreatedTime\x12 \n" +
	"\vupdatedTime\x18\v \x01(\tR\vupdatedTime\x12(\n" +
	"\x0feffectEvaluated\x18\f \x01(\bR\x0feffectEvaluated\x12\x18\n" +
	"\afinalAC\x18\r \x01(\bR\afinalAC\x12,\n" +
	"\x11effectiveGuidance\x18\x0e \x01(\bR\x11effectiveGuidance\x122\n" +
	"\x14selfExplanationScore\x18\x0f \x01(\x05R\x14selfExplanationScore\x12&\n" +
	"\x0ehintLevelTrace\x18\x10 \x03(\x05R\x0ehintLevelTrace\x12$\n" +
	"\revaluatedTime\x18\x11 \x01(\tR\revaluatedTime\"\xd7\x03\n" +
	"\x0fSocraticMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tsessionID\x18\x02 \x01(\tR\tsessionID\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\x05R\x06userID\x12\x1c\n" +
	"\tproblemID\x18\x04 \x01(\x05R\tproblemID\x12\x12\n" +
	"\x04turn\x18\x05 \x01(\x05R\x04turn\x12\x12\n" +
	"\x04role\x18\x06 \x01(\x05R\x04role\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x1a\n" +
	"\bstrategy\x18\b \x01(\tR\bstrategy\x12\x1c\n" +
	"\thintLevel\x18\t \x01(\x05R\thintLevel\x12$\n" +
	"\rguardrailPass\x18\n" +
	" \x01(\x05R\rguardrailPass\x12\x1e\n" +
	"\n" +
	"tokenCount\x18\v \x01(\x05R\n" +
	"tokenCount\x12\x16\n" +
	"\x06enable\x18\f \x01(\x05R\x06enable\x12 \n" +
	"\vcreatedTime\x18\r \x01(\tR\vcreatedTime\x12 \n" +
	"\vupdatedTime\x18\x0e \x01(\tR\vupdatedTime\x12B\n" +
	"\x0fknowledgePoints\x18\x0f \x03(\v2\x18.oj.agent.KnowledgePointR\x0fknowledgePoints\"F\n" +
	"\x0eKnowledgePoint\x12 \n" +
	"\vknowledgeID\x18\x01 \x01(\x05R\vknowledgeID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x9e\x02\n" +
	"\x14SocraticKnowledgeGap\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x05R\x06userID\x12 \n" +
	"\vknowledgeID\x18\x03 \x01(\x05R\vknowledgeID\x12$\n" +
	"\rknowledgeName\x18\x04 \x01(\tR\rknowledgeName\x12\x1c\n" +
	"\tproblemID\x18\x05 \x01(\x05R\tproblemID\x12\x1c\n" +
	"\tfrequency\x18\x06 \x01(\x05R\tfrequency\x12\x16\n" +
	"\x06enable\x18\a \x01(\x05R\x06enable\x12 \n" +
	"\vcreatedTime\x18\b \x01(\tR\vcreatedTime\x12 \n" +
	"\vupdatedTime\x18\t \x01(\tR\vupdatedTime\"\xa4\x01\n" +
	"\x18QueryKnowledgeGapListReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\x12\x1c\n" +
	"\tproblemID\x18\x02 \x01(\x05R\tproblemID\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12(\n" +
	"\x0fincludeDisabled\x18\x05 \x01(\bR\x0fincludeDisabled\"\xac\x01\n" +
	"\x18QueryKnowledgeGapListRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x122\n" +
	"\x04gaps\x18\x03 \x03(\v2\x1e.oj.agent.SocraticKnowledgeGapR\x04gaps\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x18\n" +
	"\ahasMore\x18\x05 \x01(\bR\ahasMore\"\xa4\x02\n" +
	"\x18QueryTeacherDashboardReq\x12\x1c\n" +
	"\tteacherID\x18\x01 \x01(\x05R\tteacherID\x12\x18\n" +
	"\aclassID\x18\x02 \x01(\x05R\aclassID\x12\x1c\n" +
	"\tstartTime\x18\x03 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x04 \x01(\tR\aendTime\x122\n" +
	"\x14topKnowledgeGapLimit\x18\x05 \x01(\x05R\x14topKnowledgeGapLimit\x12.\n" +
	"\x12recentSessionLimit\x18\x06 \x01(\x05R\x12recentSessionLimit\x12\x16\n" +
	"\x06userID\x18\a \x01(\x05R\x06userID\x12\x1c\n" +
	"\tproblemID\x18\b \x01(\x05R\tproblemID\"\x85\x01\n" +
	"\x18QueryTeacherDashboardRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12;\n" +
	"\asummary\x18\x03 \x01(\v2!.oj.agent.TeacherDashboardSummaryR\asummary\"\xf1\x06\n" +
	"\x17TeacherDashboardSummary\x12\x1c\n" +
	"\tteacherID\x18\x01 \x01(\x05R\tteacherID\x12\x18\n" +
	"\aclassID\x18\x02 \x01(\x05R\aclassID\x12\"\n" +
	"\fstudentCount\x18\x03 \x01(\x05R\fstudentCount\x12.\n" +
	"\x12activeSessionCount\x18\x04 \x01(\x05R\x12activeSessionCount\x12,\n" +
	"\x11totalSessionCount\x18\x05 \x01(\x05R\x11totalSessionCount\x12,\n" +
	"\x11totalMessageCount\x18\x06 \x01(\x05R\x11totalMessageCount\x12,\n" +
	"\x11knowledgeGapCount\x18\a \x01(\x05R\x11knowledgeGapCount\x12M\n" +
	"\x10topKnowledgeGaps\x18\b \x03(\v2!.oj.agent.TeacherKnowledgeGapItemR\x10topKnowledgeGaps\x12D\n" +
	"\x0erecentSessions\x18\t \x03(\v2\x1c.oj.agent.TeacherSessionItemR\x0erecentSessions\x124\n" +
	"\x15evaluatedSessionCount\x18\n" +
	" \x01(\x05R\x15evaluatedSessionCount\x120\n" +
	"\x13finalACSessionCount\x18\v \x01(\x05R\x13finalACSessionCount\x124\n" +
	"\x15effectiveSessionCount\x18\f \x01(\x05R\x15effectiveSessionCount\x12 \n" +
	"\vfinalACRate\x18\r \x01(\x01R\vfinalACRate\x124\n" +
	"\x15effectiveGuidanceRate\x18\x0e \x01(\x01R\x15effectiveGuidanceRate\x12*\n" +
	"\x10averageTurnCount\x18\x0f \x01(\x01R\x10averageTurnCount\x12@\n" +
	"\x1baverageSelfExplanationScore\x18\x10 \x01(\x01R\x1baverageSelfExplanationScore\x12G\n" +
	"\fgrowthTrends\x18\x11 \x03(\v2#.oj.agent.TeacherKnowledgeTrendItemR\fgrowthTrends\"\x9e\x02\n" +
	"\x1aQueryTeacherSessionListReq\x12\x1c\n" +
	"\tteacherID\x18\x01 \x01(\x05R\tteacherID\x12\x18\n" +
	"\aclassID\x18\x02 \x01(\x05R\aclassID\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\x05R\x06userID\x12\x1c\n" +
	"\tproblemID\x18\x04 \x01(\x05R\tproblemID\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x18\n" +
	"\akeyword\x18\x06 \x01(\tR\akeyword\x12\x1c\n" +
	"\tstartTime\x18\a \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\b \x01(\tR\aendTime\x12\x12\n" +
	"\x04page\x18\t \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\n" +
	" \x01(\x05R\x05limit\"\xb4\x01\n" +
	"\x1aQueryTeacherSessionListRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x128\n" +
	"\bsessions\x18\x03 \x03(\v2\x1c.oj.agent.TeacherSessionItemR\bsessions\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x18\n" +
	"\ahasMore\x18\x05 \x01(\bR\ahasMore\"\xdb\x03\n" +
	"\x12TeacherSessionItem\x123\n" +
	"\asession\x18\x01 \x01(\v2\x19.oj.agent.SocraticSessionR\asession\x12 \n" +
	"\vstudentName\x18\x02 \x01(\tR\vstudentName\x12$\n" +
	"\rstudentNumber\x18\x03 \x01(\tR\rstudentNumber\x12 \n" +
	"\vproblemName\x18\x04 \x01(\tR\vproblemName\x12(\n" +
	"\x0flastMessageTime\x18\x05 \x01(\tR\x0flastMessageTime\x12.\n" +
	"\x12lastMessagePreview\x18\x06 \x01(\tR\x12lastMessagePreview\x12(\n" +
	"\x0feffectEvaluated\x18\a \x01(\bR\x0feffectEvaluated\x12\x18\n" +
	"\afinalAC\x18\b \x01(\bR\afinalAC\x12,\n" +
	"\x11effectiveGuidance\x18\t \x01(\bR\x11effectiveGuidance\x122\n" +
	"\x14selfExplanationScore\x18\n" +
	" \x01(\x05R\x14selfExplanationScore\x12&\n" +
	"\x0ehintLevelTrace\x18\v \x03(\x05R\x0ehintLevelTrace\"\xab\x01\n" +
	"\x19TeacherKnowledgeTrendItem\x12\x1a\n" +
	"\bstatDate\x18\x01 \x01(\tR\bstatDate\x12$\n" +
	"\rknowledgeName\x18\x02 \x01(\tR\rknowledgeName\x12(\n" +
	"\x0foccurrenceCount\x18\x03 \x01(\x05R\x0foccurrenceCount\x12\"\n" +
	"\fstudentCount\x18\x04 \x01(\x05R\fstudentCount\"t\n" +
	"\x1cQueryTeacherSessionDetailReq\x12\x1c\n" +
	"\tteacherID\x18\x01 \x01(\x05R\tteacherID\x12\x18\n" +
	"\aclassID\x18\x02 \x01(\x05R\aclassID\x12\x1c\n" +
	"\tsessionID\x18\x03 \x01(\tR\tsessionID\"\xb8\x01\n" +
	"\x1cQueryTeacherSessionDetailRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x123\n" +
	"\asession\x18\x03 \x01(\v2\x19.oj.agent.SocraticSessionR\asession\x125\n" +
	"\bmessages\x18\x04 \x03(\v2\x19.oj.agent.SocraticMessageR\bmessages\"\x93\x02\n" +
	"\x1fQueryTeacherKnowledgeGapListReq\x12\x1c\n" +
	"\tteacherID\x18\x01 \x01(\x05R\tteacherID\x12\x18\n" +
	"\aclassID\x18\x02 \x01(\x05R\aclassID\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\x05R\x06userID\x12\x1c\n" +
	"\tproblemID\x18\x04 \x01(\x05R\tproblemID\x12 \n" +
	"\vknowledgeID\x18\x05 \x01(\x05R\vknowledgeID\x12\x1c\n" +
	"\tstartTime\x18\x06 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\a \x01(\tR\aendTime\x12\x12\n" +
	"\x04page\x18\b \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\t \x01(\x05R\x05limit\"\xb8\x01\n" +
	"\x1fQueryTeacherKnowledgeGapListRsp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x127\n" +
	"\x05items\x18\x03 \x03(\v2!.oj.agent.TeacherKnowledgeGapItemR\x05items\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\x12\x18\n" +
	"\ahasMore\x18\x05 \x01(\bR\ahasMore\"\xb5\x01\n" +
	"\x17TeacherKnowledgeGapItem\x120\n" +
	"\x03gap\x18\x01 \x01(\v2\x1e.oj.agent.SocraticKnowledgeGapR\x03gap\x12 \n" +
	"\vstudentName\x18\x02 \x01(\tR\vstudentName\x12$\n" +
	"\rstudentNumber\x18\x03 \x01(\tR\rstudentNumber\x12 \n" +
	"\vproblemName\x18\x04 \x01(\tR\vproblemName2\xb9\a\n" +
	"\vAgentServer\x12C\n" +
	"\vSocraticAsk\x12\x18.oj.agent.SocraticAskReq\x1a\x18.oj.agent.SocraticAskRsp\"\x00\x12^\n" +
	"\x14QuerySocraticSession\x12!.oj.agent.QuerySocraticSessionReq\x1a!.oj.agent.QuerySocraticSessionRsp\"\x00\x12^\n" +
	"\x14QuerySocraticHistory\x12!.oj.agent.QuerySocraticHistoryReq\x1a!.oj.agent.QuerySocraticHistoryRsp\"\x00\x12@\n" +
	"\n" +
	"EndSession\x12\x17.oj.agent.EndSessionReq\x1a\x17.oj.agent.EndSessionRsp\"\x00\x12M\n" +
	"\x11SocraticAskStream\x12\x18.oj.agent.SocraticAskReq\x1a\x1a.oj.agent.SocraticAskChunk\"\x000\x01\x12a\n" +
	"\x15QueryKnowledgeGapList\x12\".oj.agent.QueryKnowledgeGapListReq\x1a\".oj.agent.QueryKnowledgeGapListRsp\"\x00\x12a\n" +
	"\x15QueryTeacherDashboard\x12\".oj.agent.QueryTeacherDashboardReq\x1a\".oj.agent.QueryTeacherDashboardRsp\"\x00\x12g\n" +
	"\x17QueryTeacherSessionList\x12$.oj.agent.QueryTeacherSessionListReq\x1a$.oj.agent.QueryTeacherSessionListRsp\"\x00\x12m\n" +
	"\x19QueryTeacherSessionDetail\x12&.oj.agent.QueryTeacherSessionDetailReq\x1a&.oj.agent.QueryTeacherSessionDetailRsp\"\x00\x12v\n" +
	"\x1cQueryTeacherKnowledgeGapList\x12).oj.agent.QueryTeacherKnowledgeGapListReq\x1a).oj.agent.QueryTeacherKnowledgeGapListRsp\"\x00B&Z$github.com/csuJudge/agentProto/agentb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_agent_proto_goTypes = []any{
	(*SocraticAskReq)(nil),                  // 0: oj.agent.SocraticAskReq
	(*SocraticAskRsp)(nil),                  // 1: oj.agent.SocraticAskRsp
	(*SocraticAskChunk)(nil),                // 2: oj.agent.SocraticAskChunk
	(*QuerySocraticSessionReq)(nil),         // 3: oj.agent.QuerySocraticSessionReq
	(*QuerySocraticSessionRsp)(nil),         // 4: oj.agent.QuerySocraticSessionRsp
	(*QuerySocraticHistoryReq)(nil),         // 5: oj.agent.QuerySocraticHistoryReq
	(*QuerySocraticHistoryRsp)(nil),         // 6: oj.agent.QuerySocraticHistoryRsp
	(*EndSessionReq)(nil),                   // 7: oj.agent.EndSessionReq
	(*EndSessionRsp)(nil),                   // 8: oj.agent.EndSessionRsp
	(*SocraticSession)(nil),                 // 9: oj.agent.SocraticSession
	(*SocraticMessage)(nil),                 // 10: oj.agent.SocraticMessage
	(*KnowledgePoint)(nil),                  // 11: oj.agent.KnowledgePoint
	(*SocraticKnowledgeGap)(nil),            // 12: oj.agent.SocraticKnowledgeGap
	(*QueryKnowledgeGapListReq)(nil),        // 13: oj.agent.QueryKnowledgeGapListReq
	(*QueryKnowledgeGapListRsp)(nil),        // 14: oj.agent.QueryKnowledgeGapListRsp
	(*QueryTeacherDashboardReq)(nil),        // 15: oj.agent.QueryTeacherDashboardReq
	(*QueryTeacherDashboardRsp)(nil),        // 16: oj.agent.QueryTeacherDashboardRsp
	(*TeacherDashboardSummary)(nil),         // 17: oj.agent.TeacherDashboardSummary
	(*QueryTeacherSessionListReq)(nil),      // 18: oj.agent.QueryTeacherSessionListReq
	(*QueryTeacherSessionListRsp)(nil),      // 19: oj.agent.QueryTeacherSessionListRsp
	(*TeacherSessionItem)(nil),              // 20: oj.agent.TeacherSessionItem
	(*TeacherKnowledgeTrendItem)(nil),       // 21: oj.agent.TeacherKnowledgeTrendItem
	(*QueryTeacherSessionDetailReq)(nil),    // 22: oj.agent.QueryTeacherSessionDetailReq
	(*QueryTeacherSessionDetailRsp)(nil),    // 23: oj.agent.QueryTeacherSessionDetailRsp
	(*QueryTeacherKnowledgeGapListReq)(nil), // 24: oj.agent.QueryTeacherKnowledgeGapListReq
	(*QueryTeacherKnowledgeGapListRsp)(nil), // 25: oj.agent.QueryTeacherKnowledgeGapListRsp
	(*TeacherKnowledgeGapItem)(nil),         // 26: oj.agent.TeacherKnowledgeGapItem
}
var file_agent_proto_depIdxs = []int32{
	9,  // 0: oj.agent.SocraticAskRsp.session:type_name -> oj.agent.SocraticSession
	10, // 1: oj.agent.SocraticAskRsp.studentMessage:type_name -> oj.agent.SocraticMessage
	10, // 2: oj.agent.SocraticAskRsp.agentMessage:type_name -> oj.agent.SocraticMessage
	11, // 3: oj.agent.SocraticAskRsp.knowledgePoints:type_name -> oj.agent.KnowledgePoint
	11, // 4: oj.agent.SocraticAskChunk.knowledgePoints:type_name -> oj.agent.KnowledgePoint
	10, // 5: oj.agent.SocraticAskChunk.agentMessage:type_name -> oj.agent.SocraticMessage
	9,  // 6: oj.agent.QuerySocraticSessionRsp.session:type_name -> oj.agent.SocraticSession
	10, // 7: oj.agent.QuerySocraticHistoryRsp.messages:type_name -> oj.agent.SocraticMessage
	9,  // 8: oj.agent.QuerySocraticHistoryRsp.session:type_name -> oj.agent.SocraticSession
	9,  // 9: oj.agent.EndSessionRsp.session:type_name -> oj.agent.SocraticSession
	11, // 10: oj.agent.SocraticMessage.knowledgePoints:type_name -> oj.agent.KnowledgePoint
	12, // 11: oj.agent.QueryKnowledgeGapListRsp.gaps:type_name -> oj.agent.SocraticKnowledgeGap
	17, // 12: oj.agent.QueryTeacherDashboardRsp.summary:type_name -> oj.agent.TeacherDashboardSummary
	26, // 13: oj.agent.TeacherDashboardSummary.topKnowledgeGaps:type_name -> oj.agent.TeacherKnowledgeGapItem
	20, // 14: oj.agent.TeacherDashboardSummary.recentSessions:type_name -> oj.agent.TeacherSessionItem
	21, // 15: oj.agent.TeacherDashboardSummary.growthTrends:type_name -> oj.agent.TeacherKnowledgeTrendItem
	20, // 16: oj.agent.QueryTeacherSessionListRsp.sessions:type_name -> oj.agent.TeacherSessionItem
	9,  // 17: oj.agent.TeacherSessionItem.session:type_name -> oj.agent.SocraticSession
	9,  // 18: oj.agent.QueryTeacherSessionDetailRsp.session:type_name -> oj.agent.SocraticSession
	10, // 19: oj.agent.QueryTeacherSessionDetailRsp.messages:type_name -> oj.agent.SocraticMessage
	26, // 20: oj.agent.QueryTeacherKnowledgeGapListRsp.items:type_name -> oj.agent.TeacherKnowledgeGapItem
	12, // 21: oj.agent.TeacherKnowledgeGapItem.gap:type_name -> oj.agent.SocraticKnowledgeGap
	0,  // 22: oj.agent.AgentServer.SocraticAsk:input_type -> oj.agent.SocraticAskReq
	3,  // 23: oj.agent.AgentServer.QuerySocraticSession:input_type -> oj.agent.QuerySocraticSessionReq
	5,  // 24: oj.agent.AgentServer.QuerySocraticHistory:input_type -> oj.agent.QuerySocraticHistoryReq
	7,  // 25: oj.agent.AgentServer.EndSession:input_type -> oj.agent.EndSessionReq
	0,  // 26: oj.agent.AgentServer.SocraticAskStream:input_type -> oj.agent.SocraticAskReq
	13, // 27: oj.agent.AgentServer.QueryKnowledgeGapList:input_type -> oj.agent.QueryKnowledgeGapListReq
	15, // 28: oj.agent.AgentServer.QueryTeacherDashboard:input_type -> oj.agent.QueryTeacherDashboardReq
	18, // 29: oj.agent.AgentServer.QueryTeacherSessionList:input_type -> oj.agent.QueryTeacherSessionListReq
	22, // 30: oj.agent.AgentServer.QueryTeacherSessionDetail:input_type -> oj.agent.QueryTeacherSessionDetailReq
	24, // 31: oj.agent.AgentServer.QueryTeacherKnowledgeGapList:input_type -> oj.agent.QueryTeacherKnowledgeGapListReq
	1,  // 32: oj.agent.AgentServer.SocraticAsk:output_type -> oj.agent.SocraticAskRsp
	4,  // 33: oj.agent.AgentServer.QuerySocraticSession:output_type -> oj.agent.QuerySocraticSessionRsp
	6,  // 34: oj.agent.AgentServer.QuerySocraticHistory:output_type -> oj.agent.QuerySocraticHistoryRsp
	8,  // 35: oj.agent.AgentServer.EndSession:output_type -> oj.agent.EndSessionRsp
	2,  // 36: oj.agent.AgentServer.SocraticAskStream:output_type -> oj.agent.SocraticAskChunk
	14, // 37: oj.agent.AgentServer.QueryKnowledgeGapList:output_type -> oj.agent.QueryKnowledgeGapListRsp
	16, // 38: oj.agent.AgentServer.QueryTeacherDashboard:output_type -> oj.agent.QueryTeacherDashboardRsp
	19, // 39: oj.agent.AgentServer.QueryTeacherSessionList:output_type -> oj.agent.QueryTeacherSessionListRsp
	23, // 40: oj.agent.AgentServer.QueryTeacherSessionDetail:output_type -> oj.agent.QueryTeacherSessionDetailRsp
	25, // 41: oj.agent.AgentServer.QueryTeacherKnowledgeGapList:output_type -> oj.agent.QueryTeacherKnowledgeGapListRsp
	32, // [32:42] is the sub-list for method output_type
	22, // [22:32] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
